//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proteca.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceHisto {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceHisto() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Proteca.Web.Resources.ResourceHisto", typeof(ResourceHisto).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Autorégulé.
        /// </summary>
        internal static string Autoregule {
            get {
                return ResourceManager.GetString("Autoregule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        internal static string BkpCompositionEqs {
            get {
                return ResourceManager.GetString("BkpCompositionEqs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        internal static string BkpCompositionPortions {
            get {
                return ResourceManager.GetString("BkpCompositionPortions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Branchement.
        /// </summary>
        internal static string Branchement {
            get {
                return ResourceManager.GetString("Branchement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        internal static string BypassCategoriePp {
            get {
                return ResourceManager.GetString("BypassCategoriePp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        internal static string BypassPkLimitation {
            get {
                return ResourceManager.GetString("BypassPkLimitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Capacité du condensateur.
        /// </summary>
        internal static string CapaciteCondensateur {
            get {
                return ResourceManager.GetString("CapaciteCondensateur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        internal static string CapaciteCondensateurNullable {
            get {
                return ResourceManager.GetString("CapaciteCondensateurNullable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        internal static string ChildChanges {
            get {
                return ResourceManager.GetString("ChildChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Caractéristique de la pile.
        /// </summary>
        internal static string CleCaracteristiquePile {
            get {
                return ResourceManager.GetString("CleCaracteristiquePile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Catégorie PP.
        /// </summary>
        internal static string CleCategoriePp {
            get {
                return ResourceManager.GetString("CleCategoriePp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Commune.
        /// </summary>
        internal static string CleCommune {
            get {
                return ResourceManager.GetString("CleCommune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Commune d&apos;arrivée.
        /// </summary>
        internal static string CleCommuneArrivee {
            get {
                return ResourceManager.GetString("CleCommuneArrivee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Commune de départ.
        /// </summary>
        internal static string CleCommuneDepart {
            get {
                return ResourceManager.GetString("CleCommuneDepart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Déversoir.
        /// </summary>
        internal static string CleDeversoir {
            get {
                return ResourceManager.GetString("CleDeversoir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Diamètre.
        /// </summary>
        internal static string CleDiametre {
            get {
                return ResourceManager.GetString("CleDiametre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ensemble électrique.
        /// </summary>
        internal static string CleEnsElectrique {
            get {
                return ResourceManager.GetString("CleEnsElectrique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Equipement.
        /// </summary>
        internal static string CleEquipement {
            get {
                return ResourceManager.GetString("CleEquipement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clé d&apos;origine Equipement.
        /// </summary>
        internal static string CleEquipementOrigine {
            get {
                return ResourceManager.GetString("CleEquipementOrigine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liaison.
        /// </summary>
        internal static string CleLiaison {
            get {
                return ResourceManager.GetString("CleLiaison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Niveau Sensibilité.
        /// </summary>
        internal static string CleNiveauSensibilite {
            get {
                return ResourceManager.GetString("CleNiveauSensibilite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        internal static string CleNiveauSensibiliteExtended {
            get {
                return ResourceManager.GetString("CleNiveauSensibiliteExtended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom du tiers associé.
        /// </summary>
        internal static string CleNomTiersAss {
            get {
                return ResourceManager.GetString("CleNomTiersAss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Portion d&apos;integrité.
        /// </summary>
        internal static string ClePortion {
            get {
                return ResourceManager.GetString("ClePortion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à PP de rattachement (principale).
        /// </summary>
        internal static string ClePp {
            get {
                return ResourceManager.GetString("ClePp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à PP de rattachement (secondaire).
        /// </summary>
        internal static string ClePp2 {
            get {
                return ResourceManager.GetString("ClePp2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clé d&apos;origine PP.
        /// </summary>
        internal static string ClePpOrigine {
            get {
                return ResourceManager.GetString("ClePpOrigine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Redresseur.
        /// </summary>
        internal static string CleRedresseur {
            get {
                return ResourceManager.GetString("CleRedresseur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Revêtement.
        /// </summary>
        internal static string CleRevetement {
            get {
                return ResourceManager.GetString("CleRevetement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Secteur.
        /// </summary>
        internal static string CleSecteur {
            get {
                return ResourceManager.GetString("CleSecteur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type d&apos;anode.
        /// </summary>
        internal static string CleTypeAnode {
            get {
                return ResourceManager.GetString("CleTypeAnode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type de déversoir.
        /// </summary>
        internal static string CleTypeDeversoir {
            get {
                return ResourceManager.GetString("CleTypeDeversoir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type de drainage.
        /// </summary>
        internal static string CleTypeDrainage {
            get {
                return ResourceManager.GetString("CleTypeDrainage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type Equipement.
        /// </summary>
        internal static string CleTypeEq {
            get {
                return ResourceManager.GetString("CleTypeEq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type de liaison.
        /// </summary>
        internal static string CleTypeLiaison {
            get {
                return ResourceManager.GetString("CleTypeLiaison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type prise de terre.
        /// </summary>
        internal static string CleTypePriseDeTerre {
            get {
                return ResourceManager.GetString("CleTypePriseDeTerre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type de raccord isolant.
        /// </summary>
        internal static string CleTypeRi {
            get {
                return ResourceManager.GetString("CleTypeRi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Utilisateur.
        /// </summary>
        internal static string CleUtilisateur {
            get {
                return ResourceManager.GetString("CleUtilisateur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Code.
        /// </summary>
        internal static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Code GMAO.
        /// </summary>
        internal static string CodeGmao {
            get {
                return ResourceManager.GetString("CodeGmao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Code poste.
        /// </summary>
        internal static string CodePosteGaz {
            get {
                return ResourceManager.GetString("CodePosteGaz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Commentaire.
        /// </summary>
        internal static string Commentaire {
            get {
                return ResourceManager.GetString("Commentaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Commentaire de positionnement.
        /// </summary>
        internal static string CommentairePositionnement {
            get {
                return ResourceManager.GetString("CommentairePositionnement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Composition.
        /// </summary>
        internal static string Composition {
            get {
                return ResourceManager.GetString("Composition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Coordonnées WSG84 début du deversoir latitude.
        /// </summary>
        internal static string CoordDebDeversoirLat {
            get {
                return ResourceManager.GetString("CoordDebDeversoirLat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Coordonnées WSG84 début du deversoir longitude.
        /// </summary>
        internal static string CoordDebDeversoirLong {
            get {
                return ResourceManager.GetString("CoordDebDeversoirLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Coordonnées WSG84 début prise de terre latitude.
        /// </summary>
        internal static string CoordDebPriseTerreLat {
            get {
                return ResourceManager.GetString("CoordDebPriseTerreLat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Coordonnées WSG84 début prise de terre longitude.
        /// </summary>
        internal static string CoordDebPriseTerreLong {
            get {
                return ResourceManager.GetString("CoordDebPriseTerreLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Coordonnées WSG84 fin du deversoir latitude.
        /// </summary>
        internal static string CoordFinDeversoirLat {
            get {
                return ResourceManager.GetString("CoordFinDeversoirLat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Coordonnées WSG84 fin du deversoir longitude.
        /// </summary>
        internal static string CoordFinDeversoirLong {
            get {
                return ResourceManager.GetString("CoordFinDeversoirLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Coordonnées WSG84 fin prise de terre latitude.
        /// </summary>
        internal static string CoordFinPriseTerreLat {
            get {
                return ResourceManager.GetString("CoordFinPriseTerreLat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Coordonnées WSG84 fin prise de terre longitude.
        /// </summary>
        internal static string CoordFinPriseTerreLong {
            get {
                return ResourceManager.GetString("CoordFinPriseTerreLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Coordonnées WGS84 fiabilisées.
        /// </summary>
        internal static string CoordonneeGpsFiabilisee {
            get {
                return ResourceManager.GetString("CoordonneeGpsFiabilisee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        internal static string CoordonneeGpsFiabiliseeOnLoaded {
            get {
                return ResourceManager.GetString("CoordonneeGpsFiabiliseeOnLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Courants alternatifs induits.
        /// </summary>
        internal static string CourantsAlternatifsInduits {
            get {
                return ResourceManager.GetString("CourantsAlternatifsInduits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Courants vagabonds continus.
        /// </summary>
        internal static string CourantsVagabonds {
            get {
                return ResourceManager.GetString("CourantsVagabonds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date de contrôle.
        /// </summary>
        internal static string DateControle {
            get {
                return ResourceManager.GetString("DateControle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        internal static string DateControleNullable {
            get {
                return ResourceManager.GetString("DateControleNullable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        internal static string DateMajCommentaire {
            get {
                return ResourceManager.GetString("DateMajCommentaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        internal static string DateMajEquipement {
            get {
                return ResourceManager.GetString("DateMajEquipement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        internal static string DateMajPp {
            get {
                return ResourceManager.GetString("DateMajPp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date de mise en service.
        /// </summary>
        internal static string DateMiseEnService {
            get {
                return ResourceManager.GetString("DateMiseEnService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date de mise en service du redresseur.
        /// </summary>
        internal static string DateMiseEnServiceRedresseur {
            get {
                return ResourceManager.GetString("DateMiseEnServiceRedresseur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        internal static string DateMiseEnServiceRedresseurNullable {
            get {
                return ResourceManager.GetString("DateMiseEnServiceRedresseurNullable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date de mise en service télémesure.
        /// </summary>
        internal static string DateMiseEnServiceTelemesure {
            get {
                return ResourceManager.GetString("DateMiseEnServiceTelemesure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date de pose.
        /// </summary>
        internal static string DatePose {
            get {
                return ResourceManager.GetString("DatePose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date de pose du déversoir.
        /// </summary>
        internal static string DatePoseDeversoir {
            get {
                return ResourceManager.GetString("DatePoseDeversoir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date pose prise de terre.
        /// </summary>
        internal static string DatePosePriseDeTerre {
            get {
                return ResourceManager.GetString("DatePosePriseDeTerre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date prévisonnelle de renouvellement de la pile.
        /// </summary>
        internal static string DatePrevisionRenouvellementPile {
            get {
                return ResourceManager.GetString("DatePrevisionRenouvellementPile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date prévisionnelle de renouvellement du déversoir.
        /// </summary>
        internal static string DateRenouvellementDeversoir {
            get {
                return ResourceManager.GetString("DateRenouvellementDeversoir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Electrode enterrée amovible.
        /// </summary>
        internal static string ElectrodeEnterreeAmovible {
            get {
                return ResourceManager.GetString("ElectrodeEnterreeAmovible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Configuration électrique normale.
        /// </summary>
        internal static string EnumConfigElectNormale {
            get {
                return ResourceManager.GetString("EnumConfigElectNormale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Durée d&apos;enregistrement.
        /// </summary>
        internal static string EnumDureeEnrg {
            get {
                return ResourceManager.GetString("EnumDureeEnrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Etat électrique.
        /// </summary>
        internal static string EnumEtatElect {
            get {
                return ResourceManager.GetString("EnumEtatElect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Periodicité.
        /// </summary>
        internal static string EnumPeriodicite {
            get {
                return ResourceManager.GetString("EnumPeriodicite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        internal static string EnumPeriodiciteNullable {
            get {
                return ResourceManager.GetString("EnumPeriodiciteNullable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Polarisation.
        /// </summary>
        internal static string EnumPolarisation {
            get {
                return ResourceManager.GetString("EnumPolarisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Structure complexe.
        /// </summary>
        internal static string EnumStructureCplx {
            get {
                return ResourceManager.GetString("EnumStructureCplx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Surface TME.
        /// </summary>
        internal static string EnumSurfaceTme {
            get {
                return ResourceManager.GetString("EnumSurfaceTme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Surface TMS.
        /// </summary>
        internal static string EnumSurfaceTms {
            get {
                return ResourceManager.GetString("EnumSurfaceTms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Drainages associés.
        /// </summary>
        internal static string EqDrainageLiaisonsext {
            get {
                return ResourceManager.GetString("EqDrainageLiaisonsext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Soutirage associés.
        /// </summary>
        internal static string EqSoutirageLiaisonsext {
            get {
                return ResourceManager.GetString("EqSoutirageLiaisonsext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        internal static string GeoEnsElec {
            get {
                return ResourceManager.GetString("GeoEnsElec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Numéro de tronçon.
        /// </summary>
        internal static string Idtroncon {
            get {
                return ResourceManager.GetString("Idtroncon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Intensité maximale supportée.
        /// </summary>
        internal static string IntensiteMaximaleSupportee {
            get {
                return ResourceManager.GetString("IntensiteMaximaleSupportee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        internal static string IntensiteMaximaleSupporteeNullable {
            get {
                return ResourceManager.GetString("IntensiteMaximaleSupporteeNullable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Intensité de réglage.
        /// </summary>
        internal static string IntensiteReglage {
            get {
                return ResourceManager.GetString("IntensiteReglage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        internal static string IntensiteReglageNullable {
            get {
                return ResourceManager.GetString("IntensiteReglageNullable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liaison inter EE.
        /// </summary>
        internal static string LiaisonInterEe {
            get {
                return ResourceManager.GetString("LiaisonInterEe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liaison technique.
        /// </summary>
        internal static string LiaisonTechnique {
            get {
                return ResourceManager.GetString("LiaisonTechnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Libellé.
        /// </summary>
        internal static string Libelle {
            get {
                return ResourceManager.GetString("Libelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Libellé équipement tiers.
        /// </summary>
        internal static string LibelleEquipementTiers {
            get {
                return ResourceManager.GetString("LibelleEquipementTiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        internal static string LibelleNavigateToPp {
            get {
                return ResourceManager.GetString("LibelleNavigateToPp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        internal static string LibelleNavigateToPpText {
            get {
                return ResourceManager.GetString("LibelleNavigateToPpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Libellé de point commun.
        /// </summary>
        internal static string LibellePointCommun {
            get {
                return ResourceManager.GetString("LibellePointCommun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        internal static string LibellePrefix {
            get {
                return ResourceManager.GetString("LibellePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        internal static string LibellePrincipale {
            get {
                return ResourceManager.GetString("LibellePrincipale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        internal static string LibellePrincipaleRemove {
            get {
                return ResourceManager.GetString("LibellePrincipaleRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        internal static string LibelleSufix {
            get {
                return ResourceManager.GetString("LibelleSufix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        internal static string ListPartsOfLibelle {
            get {
                return ResourceManager.GetString("ListPartsOfLibelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Longueur.
        /// </summary>
        internal static string Longueur {
            get {
                return ResourceManager.GetString("Longueur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Longueur ou profondeur du déversoir.
        /// </summary>
        internal static string LongueurDeversoir {
            get {
                return ResourceManager.GetString("LongueurDeversoir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        internal static string LongueurDeversoirNullable {
            get {
                return ResourceManager.GetString("LongueurDeversoirNullable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        internal static string LongueurNullable {
            get {
                return ResourceManager.GetString("LongueurNullable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Longueur de réseau.
        /// </summary>
        internal static string LongueurReseau {
            get {
                return ResourceManager.GetString("LongueurReseau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Masse au mètre linéaire.
        /// </summary>
        internal static string MasseAuMetreLineaire {
            get {
                return ResourceManager.GetString("MasseAuMetreLineaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Niveau de protection.
        /// </summary>
        internal static string MesNiveauProtection {
            get {
                return ResourceManager.GetString("MesNiveauProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        internal static string NaviagtionPortionSecUrl {
            get {
                return ResourceManager.GetString("NaviagtionPortionSecUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        internal static string NaviagtionPP2Url {
            get {
                return ResourceManager.GetString("NaviagtionPP2Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        internal static string NavigationLiaisonInterEe {
            get {
                return ResourceManager.GetString("NavigationLiaisonInterEe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nombre de pile.
        /// </summary>
        internal static string NombrePiles {
            get {
                return ResourceManager.GetString("NombrePiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom du tiers associé.
        /// </summary>
        internal static string NomTiersAssocie {
            get {
                return ResourceManager.GetString("NomTiersAssocie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pile Associée.
        /// </summary>
        internal static string PileAssociee {
            get {
                return ResourceManager.GetString("PileAssociee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Secteurs.
        /// </summary>
        internal static string PiSecteurs {
            get {
                return ResourceManager.GetString("PiSecteurs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à PK.
        /// </summary>
        internal static string Pk {
            get {
                return ResourceManager.GetString("Pk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        internal static string PkNullable {
            get {
                return ResourceManager.GetString("PkNullable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        internal static string PointKiloDecouper {
            get {
                return ResourceManager.GetString("PointKiloDecouper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        internal static string PortionCibleItem {
            get {
                return ResourceManager.GetString("PortionCibleItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Portion integrité.
        /// </summary>
        internal static string PortionIntegrite {
            get {
                return ResourceManager.GetString("PortionIntegrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Coordonnées WGS84 latitude.
        /// </summary>
        internal static string PositionGpsLat {
            get {
                return ResourceManager.GetString("PositionGpsLat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Coordonnées WGS84 longitude.
        /// </summary>
        internal static string PositionGpsLong {
            get {
                return ResourceManager.GetString("PositionGpsLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Position par adresse postal.
        /// </summary>
        internal static string PositionnementPostal {
            get {
                return ResourceManager.GetString("PositionnementPostal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à PP.
        /// </summary>
        internal static string Pp {
            get {
                return ResourceManager.GetString("Pp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à PP.
        /// </summary>
        internal static string Pp1 {
            get {
                return ResourceManager.GetString("Pp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à PP Jumelée(s).
        /// </summary>
        internal static string PpJumelee {
            get {
                return ResourceManager.GetString("PpJumelee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à PP Jumelée(s).
        /// </summary>
        internal static string PpJumelee1 {
            get {
                return ResourceManager.GetString("PpJumelee1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à PP Poste.
        /// </summary>
        internal static string PpPoste {
            get {
                return ResourceManager.GetString("PpPoste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Présence d&apos;une télémesure.
        /// </summary>
        internal static string PresenceDUneTelemesure {
            get {
                return ResourceManager.GetString("PresenceDUneTelemesure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Présence d&apos;un éclateur.
        /// </summary>
        internal static string PresenceEclateur {
            get {
                return ResourceManager.GetString("PresenceEclateur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Présence d&apos;une PC sur l&apos;ouvrage tiers.
        /// </summary>
        internal static string PresencePcSurOuvrageTiers {
            get {
                return ResourceManager.GetString("PresencePcSurOuvrageTiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Présence réenclencheur automatique.
        /// </summary>
        internal static string PresenceReenclencheur {
            get {
                return ResourceManager.GetString("PresenceReenclencheur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Présence télémesure.
        /// </summary>
        internal static string PresenceTelemesure {
            get {
                return ResourceManager.GetString("PresenceTelemesure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Protection équipement tiers par l&apos;unité.
        /// </summary>
        internal static string ProtectionTiersParUnite {
            get {
                return ResourceManager.GetString("ProtectionTiersParUnite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Résistance initiale prise de terre.
        /// </summary>
        internal static string ResistanceInitPriseDeTerre {
            get {
                return ResourceManager.GetString("ResistanceInitPriseDeTerre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        internal static string SelectedPortion {
            get {
                return ResourceManager.GetString("SelectedPortion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimé.
        /// </summary>
        internal static string Supprime {
            get {
                return ResourceManager.GetString("Supprime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Temoin enterré amovible.
        /// </summary>
        internal static string TemoinEnterreAmovible {
            get {
                return ResourceManager.GetString("TemoinEnterreAmovible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Temoin de surface.
        /// </summary>
        internal static string TemoinMetalliqueDeSurface {
            get {
                return ResourceManager.GetString("TemoinMetalliqueDeSurface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tension de réglage.
        /// </summary>
        internal static string TensionReglage {
            get {
                return ResourceManager.GetString("TensionReglage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        internal static string TensionReglageNullable {
            get {
                return ResourceManager.GetString("TensionReglageNullable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type de fluide transporté.
        /// </summary>
        internal static string TypeFluide {
            get {
                return ResourceManager.GetString("TypeFluide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type de poste.
        /// </summary>
        internal static string TypePoste {
            get {
                return ResourceManager.GetString("TypePoste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Verrouillé.
        /// </summary>
        internal static string Verrouille {
            get {
                return ResourceManager.GetString("Verrouille", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Visite.
        /// </summary>
        internal static string Visite {
            get {
                return ResourceManager.GetString("Visite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        internal static string VisitePeriodeDebut {
            get {
                return ResourceManager.GetString("VisitePeriodeDebut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        internal static string VisitePeriodeFin {
            get {
                return ResourceManager.GetString("VisitePeriodeFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Visites.
        /// </summary>
        internal static string Visites {
            get {
                return ResourceManager.GetString("Visites", resourceCulture);
            }
        }
    }
}
