//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proteca.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationErrorResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationErrorResources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Proteca.Web.Resources.ValidationErrorResources", typeof(ValidationErrorResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le format de la latitude n&apos;est pas correct. La partie entière a un maximum de 2 chiffres et la partie décimale de 9 chiffres..
        /// </summary>
        public static string DefaultCoordonneesLatFieldErrorMessage {
            get {
                return ResourceManager.GetString("DefaultCoordonneesLatFieldErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le format de la longitude n&apos;est pas correct. La partie entière a un maximum de 2 chiffres et la partie décimale de 9 chiffres..
        /// </summary>
        public static string DefaultCoordonneesLongFieldErrorMessage {
            get {
                return ResourceManager.GetString("DefaultCoordonneesLongFieldErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le format n&apos;est pas correct. La partie entière a un maximum de {0} chiffres et la partie décimale de {1} chiffres..
        /// </summary>
        public static string DefaultDecimalFormatFieldErrorMessage {
            get {
                return ResourceManager.GetString("DefaultDecimalFormatFieldErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adresse mail invalide (ex: p.nom@grtgaz.com).
        /// </summary>
        public static string DefaultEmailFieldErrorMessage {
            get {
                return ResourceManager.GetString("DefaultEmailFieldErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La valeur saisie doit être supérieure à 0 dans le cadre d&apos;un réel.
        /// </summary>
        public static string DefaultPositiveInt {
            get {
                return ResourceManager.GetString("DefaultPositiveInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La valeur saisie ne doit pas être négative.
        /// </summary>
        public static string DefaultPositiveValue {
            get {
                return ResourceManager.GetString("DefaultPositiveValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ce champ est obligatoire..
        /// </summary>
        public static string DefaultRequiredFieldErrorMessage {
            get {
                return ResourceManager.GetString("DefaultRequiredFieldErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le format de la valeur de la résistance n&apos;est pas correcte. La partie entière a un maximum de 4 chiffres et la partie décimale de 1 chiffre..
        /// </summary>
        public static string DefaultResistanceFieldErrorMessage {
            get {
                return ResourceManager.GetString("DefaultResistanceFieldErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ce champ ne doit pas dépasser {1} caractères.
        /// </summary>
        public static string DefaultStringLengthFieldErrorMessage {
            get {
                return ResourceManager.GetString("DefaultStringLengthFieldErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cette valeur existe déjà. La valeur de ce champ doit être unique..
        /// </summary>
        public static string DefaultUniqueFieldErrorMessage {
            get {
                return ResourceManager.GetString("DefaultUniqueFieldErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La valeur saisie doit être un booléen.
        /// </summary>
        public static string DefaultValidationBoolFieldErrorMessage {
            get {
                return ResourceManager.GetString("DefaultValidationBoolFieldErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La valeur saisie doit être un réel avec maximum {0} décimale{1}.
        /// </summary>
        public static string DefaultValidationDecimalFieldErrorMessage {
            get {
                return ResourceManager.GetString("DefaultValidationDecimalFieldErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La valeur saisie doit être un réel.
        /// </summary>
        public static string DefaultValidationDoubleFieldErrorMessage {
            get {
                return ResourceManager.GetString("DefaultValidationDoubleFieldErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La valeur saisie doit être un entier.
        /// </summary>
        public static string DefaultValidationIntFieldErrorMessage {
            get {
                return ResourceManager.GetString("DefaultValidationIntFieldErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aucune unité n&apos;a été indiquée pour valider ce champ..
        /// </summary>
        public static string DefaultValidationNoUnitFieldErrorMessage {
            get {
                return ResourceManager.GetString("DefaultValidationNoUnitFieldErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La valeur saisie doit être un nombre positif.
        /// </summary>
        public static string DefaultValidationPositivFieldErrorMessage {
            get {
                return ResourceManager.GetString("DefaultValidationPositivFieldErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La valeur saisie doit être un entier positif.
        /// </summary>
        public static string DefaultValidationPositivIntFieldErrorMessage {
            get {
                return ResourceManager.GetString("DefaultValidationPositivIntFieldErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La valeur saisie doit être comprise entre {1} et {2}.
        /// </summary>
        public static string DefaultValidationRangeFieldErrorMessage {
            get {
                return ResourceManager.GetString("DefaultValidationRangeFieldErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;équipement sélectionnée est supprimée. Veuillez sélectionner un équipement valide..
        /// </summary>
        public static string DeleteStateError {
            get {
                return ResourceManager.GetString("DeleteStateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le seuil mini doit être inférieur au seuil maxi..
        /// </summary>
        public static string NiveauProtectionCompareSeuilErrorMessage {
            get {
                return ResourceManager.GetString("NiveauProtectionCompareSeuilErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le format du cout n&apos;est pas correct. La partie entière a un maximum de 6 chiffres et la partie décimale de 2 chiffres..
        /// </summary>
        public static string ParametreActionCoutFormatError {
            get {
                return ResourceManager.GetString("ParametreActionCoutFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La valeur saisie doit être un réel compris entre -9999.999 et 9999.999.
        /// </summary>
        public static string ParamGenValidationDoubleFieldErrorMessage {
            get {
                return ResourceManager.GetString("ParamGenValidationDoubleFieldErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La valeur saisie doit être un réel compris entre 0.0 et 9999.999.
        /// </summary>
        public static string ParamGenValidationPositiveDoubleFieldErrorMessage {
            get {
                return ResourceManager.GetString("ParamGenValidationPositiveDoubleFieldErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La valeur saisie doit être un entier compris entre 0 et 9999.
        /// </summary>
        public static string ParamGenValidationPositiveIntFieldErrorMessage {
            get {
                return ResourceManager.GetString("ParamGenValidationPositiveIntFieldErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le format du point kilométrique n&apos;est pas correct. La partie entière a un maximum de 5 chiffres et la partie décimale de 1 chiffre..
        /// </summary>
        public static string PPPKFormatError {
            get {
                return ResourceManager.GetString("PPPKFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le format de l&apos;intensité de réglage n&apos;est pas correct. La partie entière a un maximum de 2 chiffres et la partie décimale de 1 chiffre..
        /// </summary>
        public static string SOIntensiteReglageFormatError {
            get {
                return ResourceManager.GetString("SOIntensiteReglageFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le format de la longueur du déversoir n&apos;est pas correct. La partie entière a un maximum de 3 chiffres et la partie décimale de 2 chiffres..
        /// </summary>
        public static string SOLongueurDeversoirFormatError {
            get {
                return ResourceManager.GetString("SOLongueurDeversoirFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le format de la longueur de la masse linéaire n&apos;est pas correct. La partie entière a un maximum de 2 chiffres et la partie décimale de 2 chiffres..
        /// </summary>
        public static string SOMasseMetreFormatError {
            get {
                return ResourceManager.GetString("SOMasseMetreFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ce champ doit contenir entre {2} et {1} caractères.
        /// </summary>
        public static string StringLengthFieldErrorMessage {
            get {
                return ResourceManager.GetString("StringLengthFieldErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The security answer cannot be more than 128 characters long.
        /// </summary>
        public static string ValidationErrorBadAnswerLength {
            get {
                return ResourceManager.GetString("ValidationErrorBadAnswerLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The friendly name cannot be more than 255 characters long.
        /// </summary>
        public static string ValidationErrorBadFriendlyNameLength {
            get {
                return ResourceManager.GetString("ValidationErrorBadFriendlyNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Password must be at least 7 and at most 50 characters long.
        /// </summary>
        public static string ValidationErrorBadPasswordLength {
            get {
                return ResourceManager.GetString("ValidationErrorBadPasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A password needs to contain at least one special character e.g. @ or #.
        /// </summary>
        public static string ValidationErrorBadPasswordStrength {
            get {
                return ResourceManager.GetString("ValidationErrorBadPasswordStrength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The user name must be at least 4 and at most 255 characters long.
        /// </summary>
        public static string ValidationErrorBadUserNameLength {
            get {
                return ResourceManager.GetString("ValidationErrorBadUserNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La date saisie doit être inférieure à la date suivante : {0}.
        /// </summary>
        public static string ValidationErrorDateInf {
            get {
                return ResourceManager.GetString("ValidationErrorDateInf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La valeur saisie doit être un entier compris entre {0} et {1}.
        /// </summary>
        public static string ValidationErrorDateIntervalle {
            get {
                return ResourceManager.GetString("ValidationErrorDateIntervalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La date saisie doit être supérieure à la date suivante : {0}.
        /// </summary>
        public static string ValidationErrorDateSup {
            get {
                return ResourceManager.GetString("ValidationErrorDateSup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La date saisie doit être supérieure ou égale à la date suivante : {0}.
        /// </summary>
        public static string ValidationErrorDateSupOrEquals {
            get {
                return ResourceManager.GetString("ValidationErrorDateSupOrEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string ValidationErrorDecimal {
            get {
                return ResourceManager.GetString("ValidationErrorDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid email. An email must use the format user@company.com.
        /// </summary>
        public static string ValidationErrorInvalidEmail {
            get {
                return ResourceManager.GetString("ValidationErrorInvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid user name. It must contain only alphanumeric characters.
        /// </summary>
        public static string ValidationErrorInvalidUserName {
            get {
                return ResourceManager.GetString("ValidationErrorInvalidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Passwords do not match.
        /// </summary>
        public static string ValidationErrorPasswordConfirmationMismatch {
            get {
                return ResourceManager.GetString("ValidationErrorPasswordConfirmationMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La valeur saisie doit être positive et inférieure ou égale à la longueur de la portion ({0}).
        /// </summary>
        public static string ValidationPkFieldErrorMessage {
            get {
                return ResourceManager.GetString("ValidationPkFieldErrorMessage", resourceCulture);
            }
        }
    }
}
