///<reference path="./jaydata.d.ts" />

/*//////////////////////////////////////////////////////////////////////////////////////
////// Autogenerated by JaySvcUtil.exe http://JayData.org for more info        /////////
//////                      oData  V2  TypeScript                              /////////
//////////////////////////////////////////////////////////////////////////////////////*/


declare module ProtecaModel {
  export class UsrUtilisateur extends $data.Entity {
    constructor();
    constructor(initData: { CleUtilisateur?: number; CleSecteur?: number; GestionDesComptes?: number; CleAgence?: number; CleProfil?: number; Nom?: string; Prenom?: string; Identifiant?: string; Mail?: string; Societe?: string; Supprime?: boolean; Externe?: boolean; EstPresta?: boolean; });
    CleUtilisateur: number;
    CleSecteur: number;
    GestionDesComptes: number;
    CleAgence: number;
    CleProfil: number;
    Nom: string;
    Prenom: string;
    Identifiant: string;
    Mail: string;
    Societe: string;
    Supprime: boolean;
    Externe: boolean;
    EstPresta: boolean;
    
  }
  
}

declare module Proteca.Web.Models {
  export class ProtecaEntities extends $data.EntityContext {
    onReady(): $data.IPromise<ProtecaEntities>;
    onReady(handler: (context: ProtecaEntities) => void): $data.IPromise<ProtecaEntities>;
    
    UsrUtilisateur: $data.EntitySet<ProtecaModel.UsrUtilisateur>;
    
  }

}
