

/*//////////////////////////////////////////////////////////////////////////////////////
////// Autogenerated by JaySvcUtil.exe http://JayData.org for more info        /////////
//////                             oData  V2                                     /////////
//////////////////////////////////////////////////////////////////////////////////////*/
(function(global, $data, undefined) {

    
  $data.Entity.extend('ProtecaModel.RefParametre', {
     'CleParametre': { 'key':true,'type':'Edm.Int32','nullable':false,'computed':true },
     'Libelle': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':80 },
     'LibelleLong': { 'type':'Edm.String','maxLength':80 },
     'Valeur': { 'type':'Edm.String','maxLength':100 },
     'NumeroOrdre': { 'type':'Edm.Int32','nullable':false,'required':true },
     'CodeGroupe': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':50 },
     'TypeDeDonnee': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':50 },
     'LibUnite': { 'type':'Edm.String','maxLength':15 }
  });

  $data.Entity.extend('ProtecaModel.GeoEnsembleElectrique', {
     'Id': { 'key':true,'type':'Edm.Int32','nullable':false,'required':true },
     'CleEnsElectrique': { 'type':'Edm.Int32','nullable':false,'required':true },
     'Libelle': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':50 },
     'CleAgence': { 'type':'Edm.Int32' },
     'CleRegion': { 'type':'Edm.Int32' },
     'CleSecteur': { 'type':'Edm.Int32' },
     'EnumStructureCplx': { 'type':'Edm.Int32' }
  });

  $data.Entity.extend('ProtecaModel.PortionDates', {
     'Id': { 'key':true,'type':'Edm.Int32','nullable':false,'required':true },
     'CleEnsElectrique': { 'type':'Edm.Int32','nullable':false,'required':true },
     'ClePortion': { 'type':'Edm.Int32','nullable':false,'required':true },
     'Libelle': { 'type':'Edm.String','maxLength':80 },
     'DateEg': { 'type':'Edm.DateTime' },
     'DateEcd': { 'type':'Edm.DateTime' },
     'DateCf': { 'type':'Edm.DateTime' }
  });

  $data.Entity.extend('ProtecaModel.PpEquipement', {
     'Id': { 'key':true,'type':'Edm.Int32','nullable':false,'required':true },
     'ClePortion': { 'type':'Edm.Int32','nullable':false,'required':true },
     'ClePp': { 'type':'Edm.Int32','nullable':false,'required':true },
     'CleEquipement': { 'type':'Edm.Int32' },
     'LibelleEquipement': { 'type':'Edm.String','maxLength':70 },
     'CleTypeEq': { 'type':'Edm.Int32' },
     'LibelleType': { 'type':'Edm.String','maxLength':40 },
     'CodeEquipement': { 'type':'Edm.String','maxLength':2 },
     'LibellePp': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':40 }
  });

  $data.Entity.extend('ProtecaModel.TourneePpEq', {
     'Id': { 'key':true,'type':'Edm.Int32','nullable':false,'required':true },
     'CleTournee': { 'type':'Edm.Int32','nullable':false,'required':true },
     'LibelleTournee': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':50 },
     'EnumTypeEval': { 'type':'Edm.Int32','nullable':false,'required':true },
     'Libelle': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':70 },
     'ClePp': { 'type':'Edm.Int32' },
     'CleEquipement': { 'type':'Edm.Int32' },
     'CleSecteur': { 'type':'Edm.Int32','nullable':false,'required':true },
     'LibelleSecteur': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':50 },
     'CleAgence': { 'type':'Edm.Int32','nullable':false,'required':true },
     'CleRegion': { 'type':'Edm.Int32','nullable':false,'required':true },
     'ClePortion': { 'type':'Edm.Int32','nullable':false,'required':true },
     'CleEnsElectrique': { 'type':'Edm.Int32','nullable':false,'required':true },
     'NumeroOrdre': { 'key':true,'type':'Edm.Int32','nullable':false,'required':true }
  });

  $data.Entity.extend('ProtecaModel.AlerteDetail', {
     'CleRegion': { 'type':'Edm.Int32' },
     'CleAgence': { 'type':'Edm.Int32' },
     'CleSecteur': { 'type':'Edm.Int32' },
     'CleEnsElectrique': { 'type':'Edm.Int32' },
     'ClePortion': { 'type':'Edm.Int32' },
     'LibellePortion': { 'type':'Edm.String','maxLength':80 },
     'Pk': { 'type':'Edm.Decimal','nullable':false,'required':true },
     'Libelle': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':70 },
     'CleAlerte': { 'key':true,'type':'Edm.Int32','nullable':false,'required':true },
     'Date': { 'type':'Edm.DateTime','nullable':false,'required':true },
     'Supprime': { 'type':'Edm.Boolean','nullable':false,'required':true },
     'LibelleType': { 'type':'Edm.String','maxLength':100 },
     'Type': { 'type':'Edm.String','maxLength':100 },
     'Commentaire': { 'type':'Edm.String','maxLength':4000 },
     'CodeEquipement': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':2 }
  });

  $data.Entity.extend('ProtecaModel.GeoEnsElecPortion', {
     'Id': { 'key':true,'type':'Edm.Int32','nullable':false,'required':true },
     'ClePortion': { 'type':'Edm.Int32','nullable':false,'required':true },
     'LibellePortion': { 'type':'Edm.String','maxLength':80 },
     'LongueurPortion': { 'type':'Edm.Decimal' },
     'CleEnsElectrique': { 'type':'Edm.Int32' },
     'LibelleEe': { 'type':'Edm.String','maxLength':50 },
     'EnumStructureCplx': { 'type':'Edm.Int32' },
     'CleAgence': { 'type':'Edm.Int32','nullable':false,'required':true },
     'CleRegion': { 'type':'Edm.Int32','nullable':false,'required':true },
     'CleSecteur': { 'type':'Edm.Int32','nullable':false,'required':true },
     'NbPp': { 'type':'Edm.Int32','nullable':false,'required':true },
     'Code': { 'type':'Edm.String','maxLength':5 },
     'PortionSupprime': { 'type':'Edm.Boolean','nullable':false,'required':true }
  });

  $data.Entity.extend('ProtecaModel.GeoEnsElecPortionEqPp', {
     'Id': { 'key':true,'type':'Edm.Int32','nullable':false,'required':true },
     'ClePortion': { 'type':'Edm.Int32','nullable':false,'required':true },
     'LibellePortion': { 'type':'Edm.String','maxLength':80 },
     'CleEnsElectrique': { 'type':'Edm.Int32' },
     'LibelleEe': { 'type':'Edm.String','maxLength':50 },
     'EnumStructureCplx': { 'type':'Edm.Int32' },
     'Code': { 'type':'Edm.String','maxLength':5 },
     'CleAgence': { 'type':'Edm.Int32','nullable':false,'required':true },
     'CleRegion': { 'type':'Edm.Int32','nullable':false,'required':true },
     'CleSecteur': { 'type':'Edm.Int32','nullable':false,'required':true },
     'ClePp': { 'type':'Edm.Int32' },
     'LibellePp': { 'type':'Edm.String','maxLength':40 },
     'CleEquipement': { 'type':'Edm.Int32' },
     'LibelleEquipement': { 'type':'Edm.String','maxLength':70 },
     'CodeEquipement': { 'type':'Edm.String','maxLength':2 }
  });

  $data.Entity.extend('ProtecaModel.AnAction', {
     'CleAction': { 'key':true,'type':'Edm.Int32','nullable':false,'computed':true },
     'CleUtilisateurModification': { 'type':'Edm.Int32' },
     'EnumStatut': { 'type':'Edm.Int32','nullable':false,'required':true },
     'CleUtilisateurCreation': { 'type':'Edm.Int32','nullable':false,'required':true },
     'CleParametreAction': { 'type':'Edm.Int32' },
     'CleAnalyse': { 'type':'Edm.Int32' },
     'ConstatAnomalie': { 'type':'Edm.String','maxLength':750 },
     'DateCreation': { 'type':'Edm.DateTime','nullable':false,'required':true },
     'DateModification': { 'type':'Edm.DateTime' },
     'EntiteTraitement': { 'type':'Edm.Int32' },
     'Description': { 'type':'Edm.String','maxLength':300 },
     'Quantite': { 'type':'Edm.Int32' },
     'DateRealisationTravaux': { 'type':'Edm.DateTime' },
     'CommentaireStatut': { 'type':'Edm.String','maxLength':300 },
     'ProgrammeBudgetaire': { 'type':'Edm.String','maxLength':50 },
     'TempsTravailGlobalReel': { 'type':'Edm.Decimal' },
     'CoutGlobalReel': { 'type':'Edm.Decimal' },
     'Commentaire': { 'type':'Edm.String','maxLength':500 },
     'NumActionPc': { 'type':'Edm.String','maxLength':20 },
     'DateDebut': { 'type':'Edm.DateTime' },
     'DateCloture': { 'type':'Edm.DateTime' },
     'CleUtilisateurAgent': { 'type':'Edm.Int32','nullable':false,'required':true },
     'CleUtilisateurResponsable': { 'type':'Edm.Int32' },
     'Supprime': { 'type':'Edm.Boolean','nullable':false,'required':true },
     'TypeEval': { 'type':'Edm.Int32' },
     'AnAnalyse': { 'type':'ProtecaModel.AnAnalyse','inverseProperty':'AnAction' },
     'ParametreAction': { 'type':'ProtecaModel.ParametreAction','inverseProperty':'$$unbound' },
     'RefEnumValeur': { 'type':'ProtecaModel.RefEnumValeur','required':true,'inverseProperty':'AnAction' },
     'UsrUtilisateur': { 'type':'ProtecaModel.UsrUtilisateur','required':true,'inverseProperty':'AnAction' },
     'UsrUtilisateur1': { 'type':'ProtecaModel.UsrUtilisateur','inverseProperty':'AnAction1' },
     'PortionIntegriteAnAction': { 'type':'Array','elementType':'ProtecaModel.PortionIntegriteAnAction','inverseProperty':'AnAction' },
     'UsrUtilisateurResp': { 'type':'ProtecaModel.UsrUtilisateur','inverseProperty':'$$unbound' },
     'UsrUtilisateurAgent': { 'type':'ProtecaModel.UsrUtilisateur','required':true,'inverseProperty':'$$unbound' },
     'RefEnumValeur1': { 'type':'ProtecaModel.RefEnumValeur','inverseProperty':'AnAction1' },
     'RefEnumValeur2': { 'type':'ProtecaModel.RefEnumValeur','inverseProperty':'AnAction2' }
  });

  $data.Entity.extend('ProtecaModel.AnAnalyse', {
     'CleAnalyse': { 'key':true,'type':'Edm.Int32','nullable':false,'computed':true },
     'CleUtilisateur': { 'type':'Edm.Int32' },
     'EnumEtatPc': { 'type':'Edm.Int32' },
     'DateAnalyse': { 'type':'Edm.DateTime' },
     'Commentaire': { 'type':'Edm.String','maxLength':Number.POSITIVE_INFINITY },
     'DateEdition': { 'type':'Edm.DateTime' },
     'AnAction': { 'type':'Array','elementType':'ProtecaModel.AnAction','inverseProperty':'AnAnalyse' },
     'RefEnumValeur': { 'type':'ProtecaModel.RefEnumValeur','inverseProperty':'AnAnalyse' },
     'UsrUtilisateur': { 'type':'ProtecaModel.UsrUtilisateur','inverseProperty':'AnAnalyse' }
  });

  ProtecaModel.AnAnalyse.extend('ProtecaModel.AnAnalyseEe', {
     'CleEnsElectrique': { 'type':'Edm.Int32','nullable':false,'required':true },
     'DateDebutPeriode': { 'type':'Edm.DateTime' },
     'DateFinPeriode': { 'type':'Edm.DateTime' },
     'RefRapportAction': { 'type':'Edm.String','maxLength':50 },
     'EnsembleElectrique': { 'type':'ProtecaModel.EnsembleElectrique','required':true,'inverseProperty':'AnAnalyseEe' },
     'AnAnalyseEeVisite': { 'type':'Array','elementType':'ProtecaModel.AnAnalyseEeVisite','inverseProperty':'AnAnalyseEe' }
  });

  ProtecaModel.AnAnalyse.extend('ProtecaModel.AnAnalyseSerieMesure', {
     'CleVisite': { 'type':'Edm.Int32','nullable':false,'required':true },
     'Alertes': { 'type':'Array','elementType':'ProtecaModel.Alerte','inverseProperty':'AnAnalyseSerieMesure' },
     'Visite': { 'type':'ProtecaModel.Visite','required':true,'inverseProperty':'AnAnalyseSerieMesure' }
  });

  $data.Entity.extend('ProtecaModel.CategoriePp', {
     'CleCategoriePp': { 'key':true,'type':'Edm.Int32','nullable':false,'computed':true },
     'CleTypeEq': { 'type':'Edm.Int32' },
     'CleNiveauSensibilite': { 'type':'Edm.Int32','nullable':false,'required':true },
     'Libelle': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':30 },
     'NonLieAUnEquipement': { 'type':'Edm.Boolean','nullable':false,'required':true },
     'NumeroOrdre': { 'type':'Edm.Int32','nullable':false,'required':true },
     'TypeEquipement': { 'type':'ProtecaModel.TypeEquipement','inverseProperty':'CategoriePp' },
     'RefNiveauSensibilitePp': { 'type':'ProtecaModel.RefNiveauSensibilitePp','required':true,'inverseProperty':'CategoriePp' },
     'HistoPp': { 'type':'Array','elementType':'ProtecaModel.HistoPp','inverseProperty':'CategoriePp' },
     'Pps': { 'type':'Array','elementType':'ProtecaModel.Pp','inverseProperty':'CategoriePp' },
     'PpTmp': { 'type':'Array','elementType':'ProtecaModel.PpTmp','inverseProperty':'CategoriePp' }
  });

  $data.Entity.extend('ProtecaModel.Composition', {
     'CleComposition': { 'key':true,'type':'Edm.Int32','nullable':false,'computed':true },
     'CleTournee': { 'type':'Edm.Int32','nullable':false,'required':true },
     'ClePp': { 'type':'Edm.Int32' },
     'CleEquipement': { 'type':'Edm.Int32' },
     'ClePortion': { 'type':'Edm.Int32' },
     'CleEnsElectrique': { 'type':'Edm.Int32' },
     'EnumTypeEval': { 'type':'Edm.Int32','nullable':false,'required':true },
     'NumeroOrdre': { 'type':'Edm.Int32','nullable':false,'required':true },
     'CleEqTmp': { 'type':'Edm.Int32' },
     'EnsembleElectrique': { 'type':'ProtecaModel.EnsembleElectrique','inverseProperty':'Compositions' },
     'EqEquipement': { 'type':'ProtecaModel.EqEquipement','inverseProperty':'Compositions' },
     'PortionIntegrite': { 'type':'ProtecaModel.PortionIntegrite','inverseProperty':'Compositions' },
     'Pp': { 'type':'ProtecaModel.Pp','inverseProperty':'Compositions' },
     'RefEnumValeur': { 'type':'ProtecaModel.RefEnumValeur','required':true,'inverseProperty':'Compositions' },
     'Tournee': { 'type':'ProtecaModel.Tournee','required':true,'inverseProperty':'Compositions' },
     'EqEquipementTmp': { 'type':'ProtecaModel.EqEquipementTmp','inverseProperty':'Compositions' }
  });

  $data.Entity.extend('ProtecaModel.EnsembleElectrique', {
     'CleEnsElectrique': { 'key':true,'type':'Edm.Int32','nullable':false,'computed':true },
     'EnumPeriodicite': { 'type':'Edm.Int32','nullable':false,'required':true },
     'EnumStructureCplx': { 'type':'Edm.Int32' },
     'Code': { 'type':'Edm.String','maxLength':5 },
     'Libelle': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':50 },
     'LongueurReseau': { 'type':'Edm.Decimal','nullable':false,'required':true },
     'Commentaire': { 'type':'Edm.String','maxLength':500 },
     'DateMajCommentaire': { 'type':'Edm.DateTime' },
     'Supprime': { 'type':'Edm.Boolean','nullable':false,'required':true },
     'AnAnalyseEe': { 'type':'Array','elementType':'ProtecaModel.AnAnalyseEe','inverseProperty':'EnsembleElectrique' },
     'Compositions': { 'type':'Array','elementType':'ProtecaModel.Composition','inverseProperty':'EnsembleElectrique' },
     'RefEnumValeur': { 'type':'ProtecaModel.RefEnumValeur','required':true,'inverseProperty':'EnsembleElectrique' },
     'RefEnumValeur1': { 'type':'ProtecaModel.RefEnumValeur','inverseProperty':'EnsembleElectrique1' },
     'LogOuvrage': { 'type':'Array','elementType':'ProtecaModel.LogOuvrage','inverseProperty':'EnsembleElectrique' },
     'PortionIntegrite': { 'type':'Array','elementType':'ProtecaModel.PortionIntegrite','inverseProperty':'EnsembleElectrique' }
  });

  $data.Entity.extend('ProtecaModel.EqDrainageLiaisonsext', {
     'CleDrainageLext': { 'key':true,'type':'Edm.Int32','nullable':false,'computed':true },
     'CleLiaisonExt': { 'type':'Edm.Int32','nullable':false,'required':true },
     'CleDrainage': { 'type':'Edm.Int32','nullable':false,'required':true },
     'EqDrainage': { 'type':'ProtecaModel.EqDrainage','required':true,'inverseProperty':'EqDrainageLiaisonsext' },
     'EqLiaisonExterne': { 'type':'ProtecaModel.EqLiaisonExterne','required':true,'inverseProperty':'EqDrainageLiaisonsext' }
  });

  $data.Entity.extend('ProtecaModel.EqEquipement', {
     'CleEquipement': { 'key':true,'type':'Edm.Int32','nullable':false,'computed':true },
     'CleEquipementOrigine': { 'type':'Edm.Int32' },
     'ClePp': { 'type':'Edm.Int32','nullable':false,'required':true },
     'CleTypeEq': { 'type':'Edm.Int32','nullable':false,'required':true },
     'CleUtilisateur': { 'type':'Edm.Int32' },
     'Libelle': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':70 },
     'Commentaire': { 'type':'Edm.String','maxLength':500 },
     'DateMiseEnService': { 'type':'Edm.DateTime' },
     'Supprime': { 'type':'Edm.Boolean','nullable':false,'required':true },
     'DateMajCommentaire': { 'type':'Edm.DateTime' },
     'DateMajEquipement': { 'type':'Edm.DateTime','nullable':false,'required':true },
     'Compositions': { 'type':'Array','elementType':'ProtecaModel.Composition','inverseProperty':'EqEquipement' },
     'UsrUtilisateur': { 'type':'ProtecaModel.UsrUtilisateur','inverseProperty':'EqEquipement' },
     'Pp': { 'type':'ProtecaModel.Pp','required':true,'inverseProperty':'EqEquipement' },
     'TypeEquipement': { 'type':'ProtecaModel.TypeEquipement','required':true,'inverseProperty':'EqEquipement' },
     'EqEquipementEqEquipement': { 'type':'Array','elementType':'ProtecaModel.EqEquipement','inverseProperty':'EqEquipement2' },
     'EqEquipement2': { 'type':'ProtecaModel.EqEquipement','inverseProperty':'EqEquipementEqEquipement' },
     'EqRaccordIsolant1': { 'type':'Array','elementType':'ProtecaModel.EqRaccordIsolant','inverseProperty':'EqEquipement1' },
     'Images': { 'type':'Array','elementType':'ProtecaModel.Image','inverseProperty':'EqEquipement' },
     'LogOuvrage': { 'type':'Array','elementType':'ProtecaModel.LogOuvrage','inverseProperty':'EqEquipement' },
     'MesNiveauProtection': { 'type':'Array','elementType':'ProtecaModel.MesNiveauProtection','inverseProperty':'EqEquipement' },
     'Visites': { 'type':'Array','elementType':'ProtecaModel.Visite','inverseProperty':'EqEquipement' }
  });

  ProtecaModel.EqEquipement.extend('ProtecaModel.EqAnodeGalvanique', {
     'CleTypeAnode': { 'type':'Edm.Int32','nullable':false,'required':true },
     'PileAssociee': { 'type':'Edm.Boolean','nullable':false,'required':true },
     'RefSousTypeOuvrage': { 'type':'ProtecaModel.RefSousTypeOuvrage','required':true,'inverseProperty':'EqAnodeGalvanique' }
  });

  ProtecaModel.EqEquipement.extend('ProtecaModel.EqDispoEcoulementCourantsAlternatifs', {
     'CleTypePriseDeTerre': { 'type':'Edm.Int32','nullable':false,'required':true },
     'CapaciteCondensateur': { 'type':'Edm.Int32','nullable':false,'required':true },
     'DatePosePriseDeTerre': { 'type':'Edm.DateTime' },
     'ResistanceInitPriseDeTerre': { 'type':'Edm.Decimal' },
     'CoordDebPriseTerreLat': { 'type':'Edm.Decimal' },
     'CoordDebPriseTerreLong': { 'type':'Edm.Decimal' },
     'CoordFinPriseTerreLat': { 'type':'Edm.Decimal' },
     'CoordFinPriseTerreLong': { 'type':'Edm.Decimal' },
     'DateMiseEnServiceTelemesure': { 'type':'Edm.DateTime' },
     'PresenceTelemesure': { 'type':'Edm.Boolean','nullable':false,'required':true },
     'RefSousTypeOuvrage': { 'type':'ProtecaModel.RefSousTypeOuvrage','required':true,'inverseProperty':'EqDispoEcoulementCourantsAlternatifs' }
  });

  ProtecaModel.EqEquipement.extend('ProtecaModel.EqDrainage', {
     'CleTypeDrainage': { 'type':'Edm.Int32','nullable':false,'required':true },
     'IntensiteMaximaleSupportee': { 'type':'Edm.Int32','nullable':false,'required':true },
     'DateMiseEnServiceTelemesure': { 'type':'Edm.DateTime' },
     'PresenceTelemesure': { 'type':'Edm.Boolean','nullable':false,'required':true },
     'EqDrainageLiaisonsext': { 'type':'Array','elementType':'ProtecaModel.EqDrainageLiaisonsext','inverseProperty':'EqDrainage' },
     'RefSousTypeOuvrage': { 'type':'ProtecaModel.RefSousTypeOuvrage','required':true,'inverseProperty':'EqDrainage' }
  });

  ProtecaModel.EqEquipement.extend('ProtecaModel.EqLiaisonExterne', {
     'CleTypeLiaison': { 'type':'Edm.Int32','nullable':false,'required':true },
     'CleNomTiersAss': { 'type':'Edm.Int32','nullable':false,'required':true },
     'PresencePcSurOuvrageTiers': { 'type':'Edm.Boolean','nullable':false,'required':true },
     'ProtectionTiersParUnite': { 'type':'Edm.Boolean','nullable':false,'required':true },
     'TypeFluide': { 'type':'Edm.String','maxLength':30 },
     'LiaisonTechnique': { 'type':'Edm.Boolean','nullable':false,'required':true },
     'LibelleEquipementTiers': { 'type':'Edm.String','maxLength':50 },
     'LibellePointCommun': { 'type':'Edm.String','maxLength':30 },
     'DateMiseEnServiceTelemesure': { 'type':'Edm.DateTime' },
     'PresenceTelemesure': { 'type':'Edm.Boolean','nullable':false,'required':true },
     'EqDrainageLiaisonsext': { 'type':'Array','elementType':'ProtecaModel.EqDrainageLiaisonsext','inverseProperty':'EqLiaisonExterne' },
     'RefSousTypeOuvrage': { 'type':'ProtecaModel.RefSousTypeOuvrage','required':true,'inverseProperty':'EqLiaisonExterne' },
     'RefSousTypeOuvrage1': { 'type':'ProtecaModel.RefSousTypeOuvrage','required':true,'inverseProperty':'EqLiaisonExterne1' },
     'EqSoutirageLiaisonsext': { 'type':'Array','elementType':'ProtecaModel.EqSoutirageLiaisonsext','inverseProperty':'EqLiaisonExterne' }
  });

  ProtecaModel.EqEquipement.extend('ProtecaModel.EqRaccordIsolant', {
     'CleTypeRi': { 'type':'Edm.Int32','nullable':false,'required':true },
     'ClePp2': { 'type':'Edm.Int32' },
     'EnumConfigElectNormale': { 'type':'Edm.Int32' },
     'EnumEtatElect': { 'type':'Edm.Int32','nullable':false,'required':true },
     'CleLiaison': { 'type':'Edm.Int32' },
     'PresenceEclateur': { 'type':'Edm.Boolean','nullable':false,'required':true },
     'CleTypeLiaison': { 'type':'Edm.Int32' },
     'EqEquipement1': { 'type':'ProtecaModel.EqEquipement','inverseProperty':'EqRaccordIsolant1' },
     'RefEnumValeur': { 'type':'ProtecaModel.RefEnumValeur','inverseProperty':'EqRaccordIsolant' },
     'RefEnumValeur1': { 'type':'ProtecaModel.RefEnumValeur','required':true,'inverseProperty':'EqRaccordIsolant1' },
     'Pp2': { 'type':'ProtecaModel.Pp','inverseProperty':'EqRaccordIsolant' },
     'RefSousTypeOuvrage': { 'type':'ProtecaModel.RefSousTypeOuvrage','inverseProperty':'EqRaccordIsolant' },
     'RefSousTypeOuvrage1': { 'type':'ProtecaModel.RefSousTypeOuvrage','required':true,'inverseProperty':'EqRaccordIsolant1' }
  });

  ProtecaModel.EqEquipement.extend('ProtecaModel.EqFourreauMetallique', {
     'ClePp2': { 'type':'Edm.Int32' },
     'Longueur': { 'type':'Edm.Int32','nullable':false,'required':true },
     'Pp2': { 'type':'ProtecaModel.Pp','inverseProperty':'EqFourreauMetallique' }
  });

  ProtecaModel.EqEquipement.extend('ProtecaModel.EqLiaisonInterne', {
     'ClePp2': { 'type':'Edm.Int32','nullable':false,'required':true },
     'CleTypeLiaison': { 'type':'Edm.Int32','nullable':false,'required':true },
     'CleLiaisonInterEe': { 'type':'Edm.Int32' },
     'LiaisonInterEe': { 'type':'Edm.Boolean','nullable':false,'required':true },
     'LibellePointCommun': { 'type':'Edm.String','maxLength':30 },
     'DateMiseEnServiceTelemesure': { 'type':'Edm.DateTime' },
     'PresenceTelemesure': { 'type':'Edm.Boolean','nullable':false,'required':true },
     'Pp2': { 'type':'ProtecaModel.Pp','required':true,'inverseProperty':'EqLiaisonInterne' },
     'RefSousTypeOuvrage': { 'type':'ProtecaModel.RefSousTypeOuvrage','required':true,'inverseProperty':'EqLiaisonInterne' },
     'EqLiaisonInterne1': { 'type':'Array','elementType':'ProtecaModel.EqLiaisonInterne','inverseProperty':'EqLiaisonInterne2' },
     'EqLiaisonInterne2': { 'type':'ProtecaModel.EqLiaisonInterne','inverseProperty':'EqLiaisonInterne1' }
  });

  ProtecaModel.EqEquipement.extend('ProtecaModel.EqPile', {
     'CleCaracteristiquePile': { 'type':'Edm.Int32','nullable':false,'required':true },
     'CleTypeDeversoir': { 'type':'Edm.Int32','nullable':false,'required':true },
     'DateRenouvellementDeversoir': { 'type':'Edm.DateTime' },
     'DatePrevisionRenouvellementPile': { 'type':'Edm.DateTime' },
     'NombrePiles': { 'type':'Edm.Int32' },
     'RefEnumValeur': { 'type':'ProtecaModel.RefEnumValeur','required':true,'inverseProperty':'EqPile' },
     'RefSousTypeOuvrage': { 'type':'ProtecaModel.RefSousTypeOuvrage','required':true,'inverseProperty':'EqPile' }
  });

  ProtecaModel.EqEquipement.extend('ProtecaModel.EqSoutirage', {
     'CleDeversoir': { 'type':'Edm.Int32','nullable':false,'required':true },
     'CleRedresseur': { 'type':'Edm.Int32','nullable':false,'required':true },
     'Autoregule': { 'type':'Edm.Boolean','nullable':false,'required':true },
     'DateControle': { 'type':'Edm.DateTime','nullable':false,'required':true },
     'DateMiseEnServiceRedresseur': { 'type':'Edm.DateTime','nullable':false,'required':true },
     'DatePoseDeversoir': { 'type':'Edm.DateTime' },
     'DateRenouvellementDeversoir': { 'type':'Edm.DateTime' },
     'IntensiteReglage': { 'type':'Edm.Decimal','nullable':false,'required':true },
     'LongueurDeversoir': { 'type':'Edm.Decimal','nullable':false,'required':true },
     'MasseAuMetreLineaire': { 'type':'Edm.Decimal' },
     'PresenceReenclencheur': { 'type':'Edm.Boolean','nullable':false,'required':true },
     'TensionReglage': { 'type':'Edm.Int32','nullable':false,'required':true },
     'CoordDebDeversoirLat': { 'type':'Edm.Decimal' },
     'CoordDebDeversoirLong': { 'type':'Edm.Decimal' },
     'CoordFinDeversoirLat': { 'type':'Edm.Decimal' },
     'CoordFinDeversoirLong': { 'type':'Edm.Decimal' },
     'DateMiseEnServiceTelemesure': { 'type':'Edm.DateTime' },
     'PresenceTelemesure': { 'type':'Edm.Boolean','nullable':false,'required':true },
     'EqSoutirageLiaisonsext': { 'type':'Array','elementType':'ProtecaModel.EqSoutirageLiaisonsext','inverseProperty':'EqSoutirage' },
     'RefSousTypeOuvrage': { 'type':'ProtecaModel.RefSousTypeOuvrage','required':true,'inverseProperty':'EqSoutirage' },
     'RefSousTypeOuvrage1': { 'type':'ProtecaModel.RefSousTypeOuvrage','required':true,'inverseProperty':'EqSoutirage1' }
  });

  ProtecaModel.EqEquipement.extend('ProtecaModel.EqPostegaz', {
     'CodePosteGaz': { 'type':'Edm.String','maxLength':30 },
     'TypePoste': { 'type':'Edm.String','maxLength':50 }
  });

  ProtecaModel.EqEquipement.extend('ProtecaModel.EqTiersCroiseSansLiaison', {
     'NomTiersAssocie': { 'type':'Edm.String','maxLength':30 },
     'PresencePcSurOuvrageTiers': { 'type':'Edm.Boolean','nullable':false,'required':true },
     'TypeFluide': { 'type':'Edm.String','maxLength':30 }
  });

  $data.Entity.extend('ProtecaModel.EqEquipementTmp', {
     'CleEqTmp': { 'key':true,'type':'Edm.Int32','nullable':false,'computed':true },
     'ClePp': { 'type':'Edm.Int32','nullable':false,'required':true },
     'CleTypeEq': { 'type':'Edm.Int32','nullable':false,'required':true },
     'Libelle': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':70 },
     'EstValide': { 'type':'Edm.Boolean','nullable':false,'required':true },
     'DateValidation': { 'type':'Edm.DateTime' },
     'Pp2': { 'type':'ProtecaModel.Pp','required':true,'inverseProperty':'EqEquipementTmp' },
     'TypeEquipement': { 'type':'ProtecaModel.TypeEquipement','required':true,'inverseProperty':'EqEquipementTmp' },
     'Visites': { 'type':'Array','elementType':'ProtecaModel.Visite','inverseProperty':'EqEquipementTmp' },
     'Compositions': { 'type':'Array','elementType':'ProtecaModel.Composition','inverseProperty':'EqEquipementTmp' }
  });

  $data.Entity.extend('ProtecaModel.EqSoutirageLiaisonsext', {
     'CleSoutirageLext': { 'key':true,'type':'Edm.Int32','nullable':false,'computed':true },
     'CleLiaisonExt': { 'type':'Edm.Int32','nullable':false,'required':true },
     'CleSoutirage': { 'type':'Edm.Int32','nullable':false,'required':true },
     'EqLiaisonExterne': { 'type':'ProtecaModel.EqLiaisonExterne','required':true,'inverseProperty':'EqSoutirageLiaisonsext' },
     'EqSoutirage': { 'type':'ProtecaModel.EqSoutirage','required':true,'inverseProperty':'EqSoutirageLiaisonsext' }
  });

  $data.Entity.extend('ProtecaModel.GeoAgence', {
     'CleAgence': { 'key':true,'type':'Edm.Int32','nullable':false,'computed':true },
     'CleRegion': { 'type':'Edm.Int32','nullable':false,'required':true },
     'LibelleAgence': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':50 },
     'LibelleAbregeAgence': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':20 },
     'CodeAgence': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':3 },
     'GeoRegion': { 'type':'ProtecaModel.GeoRegion','required':true,'inverseProperty':'GeoAgence' },
     'GeoSecteur': { 'type':'Array','elementType':'ProtecaModel.GeoSecteur','inverseProperty':'GeoAgence' },
     'InsInstrument': { 'type':'Array','elementType':'ProtecaModel.InsInstrument','inverseProperty':'GeoAgence' },
     'UsrUtilisateur': { 'type':'Array','elementType':'ProtecaModel.UsrUtilisateur','inverseProperty':'GeoAgence' }
  });

  $data.Entity.extend('ProtecaModel.GeoRegion', {
     'CleRegion': { 'key':true,'type':'Edm.Int32','nullable':false,'computed':true },
     'LibelleRegion': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':50 },
     'CodeRegion': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':4 },
     'LibelleAbregeRegion': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':20 },
     'GeoAgence': { 'type':'Array','elementType':'ProtecaModel.GeoAgence','inverseProperty':'GeoRegion' },
     'InsInstrument': { 'type':'Array','elementType':'ProtecaModel.InsInstrument','inverseProperty':'GeoRegion' }
  });

  $data.Entity.extend('ProtecaModel.GeoSecteur', {
     'CleSecteur': { 'key':true,'type':'Edm.Int32','nullable':false,'computed':true },
     'CleAgence': { 'type':'Edm.Int32','nullable':false,'required':true },
     'LibelleSecteur': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':50 },
     'LibelleAbregeSecteur': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':20 },
     'CodeSecteur': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':3 },
     'GeoAgence': { 'type':'ProtecaModel.GeoAgence','required':true,'inverseProperty':'GeoSecteur' },
     'InsInstrument': { 'type':'Array','elementType':'ProtecaModel.InsInstrument','inverseProperty':'GeoSecteur' },
     'PiSecteurs': { 'type':'Array','elementType':'ProtecaModel.PiSecteurs','inverseProperty':'GeoSecteur' },
     'Pps': { 'type':'Array','elementType':'ProtecaModel.Pp','inverseProperty':'GeoSecteur' },
     'UsrUtilisateur': { 'type':'Array','elementType':'ProtecaModel.UsrUtilisateur','inverseProperty':'GeoSecteur' }
  });

  $data.Entity.extend('ProtecaModel.HistoAdmin', {
     'CleHistoAdmin': { 'key':true,'type':'Edm.Int32','nullable':false,'computed':true },
     'EnumTypeModification': { 'type':'Edm.Int32','nullable':false,'required':true },
     'IdConnecte': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':70 },
     'NomConnecte': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':20 },
     'PrenomConnecte': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':15 },
     'IdUtilisateur': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':70 },
     'NomUtilisateur': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':20 },
     'PrenomUtilisateur': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':15 },
     'TypeCompte': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':30 },
     'DateModification': { 'type':'Edm.DateTime','nullable':false,'required':true },
     'RefEnumValeur': { 'type':'ProtecaModel.RefEnumValeur','required':true,'inverseProperty':'HistoAdmin' }
  });

  $data.Entity.extend('ProtecaModel.HistoEquipement', {
     'CleHistoEquipement': { 'key':true,'type':'Edm.Int32','nullable':false,'computed':true },
     'CleTypeEq': { 'type':'Edm.Int32','nullable':false,'required':true },
     'CleLogOuvrage': { 'type':'Edm.Int32','nullable':false,'required':true },
     'LibellePp': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':50 },
     'LibellePortion': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':80 },
     'Libelle': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':70 },
     'Commentaire': { 'type':'Edm.String','maxLength':500 },
     'DateMiseEnService': { 'type':'Edm.DateTime' },
     'Supprime': { 'type':'Edm.Boolean','nullable':false,'required':true },
     'DateMajCommentaire': { 'type':'Edm.DateTime' },
     'DateMajEquipement': { 'type':'Edm.DateTime','nullable':false,'required':true },
     'LogOuvrage': { 'type':'ProtecaModel.LogOuvrage','required':true,'inverseProperty':'HistoEquipement' },
     'TypeEquipement': { 'type':'ProtecaModel.TypeEquipement','required':true,'inverseProperty':'HistoEquipement' },
     'LogOuvrage1': { 'type':'Array','elementType':'ProtecaModel.LogOuvrage','inverseProperty':'HistoEquipement1' }
  });

  ProtecaModel.HistoEquipement.extend('ProtecaModel.HistoEqAnodeGalvanique', {
     'CleTypeAnode': { 'type':'Edm.Int32','nullable':false,'required':true },
     'PileAssociee': { 'type':'Edm.Boolean','nullable':false,'required':true },
     'RefSousTypeOuvrage': { 'type':'ProtecaModel.RefSousTypeOuvrage','required':true,'inverseProperty':'HistoEqAnodeGalvanique' }
  });

  ProtecaModel.HistoEquipement.extend('ProtecaModel.HistoEqDispoEcoulementCourantsAlternatifs', {
     'CleTypePriseDeTerre': { 'type':'Edm.Int32','nullable':false,'required':true },
     'CapaciteCondensateur': { 'type':'Edm.Int32','nullable':false,'required':true },
     'DatePosePriseDeTerre': { 'type':'Edm.DateTime' },
     'ResistanceInitPriseDeTerre': { 'type':'Edm.Decimal' },
     'CoordDebPriseTerreLat': { 'type':'Edm.Decimal' },
     'CoordDebPriseTerreLong': { 'type':'Edm.Decimal' },
     'CoordFinPriseTerreLat': { 'type':'Edm.Decimal' },
     'CoordFinPriseTerreLong': { 'type':'Edm.Decimal' },
     'DateMiseEnServiceTelemesure': { 'type':'Edm.DateTime' },
     'PresenceTelemesure': { 'type':'Edm.Boolean','nullable':false,'required':true },
     'RefSousTypeOuvrage': { 'type':'ProtecaModel.RefSousTypeOuvrage','required':true,'inverseProperty':'HistoEqDispoEcoulementCourantsAlternatifs' }
  });

  ProtecaModel.HistoEquipement.extend('ProtecaModel.HistoEqDrainage', {
     'CleTypeDrainage': { 'type':'Edm.Int32','nullable':false,'required':true },
     'IntensiteMaximaleSupportee': { 'type':'Edm.Int32','nullable':false,'required':true },
     'DateMiseEnServiceTelemesure': { 'type':'Edm.DateTime' },
     'PresenceTelemesure': { 'type':'Edm.Boolean','nullable':false,'required':true },
     'RefSousTypeOuvrage': { 'type':'ProtecaModel.RefSousTypeOuvrage','required':true,'inverseProperty':'HistoEqDrainage' }
  });

  ProtecaModel.HistoEquipement.extend('ProtecaModel.HistoEqLiaisonExterne', {
     'CleTypeLiaison': { 'type':'Edm.Int32','nullable':false,'required':true },
     'PresencePcSurOuvrageTiers': { 'type':'Edm.Boolean','nullable':false,'required':true },
     'ProtectionTiersParUnite': { 'type':'Edm.Boolean','nullable':false,'required':true },
     'TypeFluide': { 'type':'Edm.String','maxLength':30 },
     'LiaisonTechnique': { 'type':'Edm.Boolean','nullable':false,'required':true },
     'LibelleEquipementTiers': { 'type':'Edm.String','maxLength':50 },
     'NomTiers': { 'type':'Edm.String','maxLength':30 },
     'LibellePointCommun': { 'type':'Edm.String','maxLength':30 },
     'DateMiseEnServiceTelemesure': { 'type':'Edm.DateTime' },
     'PresenceTelemesure': { 'type':'Edm.Boolean','nullable':false,'required':true },
     'RefSousTypeOuvrage': { 'type':'ProtecaModel.RefSousTypeOuvrage','required':true,'inverseProperty':'HistoEqLiaisonExterne' }
  });

  ProtecaModel.HistoEquipement.extend('ProtecaModel.HistoEqLiaisonInterne', {
     'CleTypeLiaison': { 'type':'Edm.Int32','nullable':false,'required':true },
     'LiaisonInterEe': { 'type':'Edm.Boolean','nullable':false,'required':true },
     'LibellePp2': { 'type':'Edm.String','maxLength':50 },
     'LibellePortionPp2': { 'type':'Edm.String','maxLength':80 },
     'LibellePointCommun': { 'type':'Edm.String','maxLength':30 },
     'DateMiseEnServiceTelemesure': { 'type':'Edm.DateTime' },
     'PresenceTelemesure': { 'type':'Edm.Boolean','nullable':false,'required':true },
     'LibelleDoublonInterEe': { 'type':'Edm.String','maxLength':60 },
     'RefSousTypeOuvrage': { 'type':'ProtecaModel.RefSousTypeOuvrage','required':true,'inverseProperty':'HistoEqLiaisonInterne' }
  });

  ProtecaModel.HistoEquipement.extend('ProtecaModel.HistoEqPile', {
     'CleTypeDeversoir': { 'type':'Edm.Int32','nullable':false,'required':true },
     'CleCaracteristiquePile': { 'type':'Edm.Int32','nullable':false,'required':true },
     'DatePrevisionRenouvellementPile': { 'type':'Edm.DateTime' },
     'DateRenouvellementDeversoir': { 'type':'Edm.DateTime' },
     'NombrePiles': { 'type':'Edm.Int32' },
     'RefEnumValeur': { 'type':'ProtecaModel.RefEnumValeur','required':true,'inverseProperty':'HistoEqPile' },
     'RefSousTypeOuvrage': { 'type':'ProtecaModel.RefSousTypeOuvrage','required':true,'inverseProperty':'HistoEqPile' }
  });

  ProtecaModel.HistoEquipement.extend('ProtecaModel.HistoEqRaccordIsolant', {
     'EnumEtatElect': { 'type':'Edm.Int32','nullable':false,'required':true },
     'CleTypeRi': { 'type':'Edm.Int32','nullable':false,'required':true },
     'CleTypeLiaison': { 'type':'Edm.Int32' },
     'EnumConfigElectNormale': { 'type':'Edm.Int32' },
     'PresenceEclateur': { 'type':'Edm.Boolean','nullable':false,'required':true },
     'LibelleLiaison': { 'type':'Edm.String','maxLength':50 },
     'LibellePp2': { 'type':'Edm.String','maxLength':50 },
     'LibellePortionPp2': { 'type':'Edm.String','maxLength':80 },
     'RefEnumValeur': { 'type':'ProtecaModel.RefEnumValeur','inverseProperty':'HistoEqRaccordIsolant' },
     'RefEnumValeur1': { 'type':'ProtecaModel.RefEnumValeur','required':true,'inverseProperty':'HistoEqRaccordIsolant1' },
     'RefSousTypeOuvrage': { 'type':'ProtecaModel.RefSousTypeOuvrage','required':true,'inverseProperty':'HistoEqRaccordIsolant' },
     'RefSousTypeOuvrage1': { 'type':'ProtecaModel.RefSousTypeOuvrage','inverseProperty':'HistoEqRaccordIsolant1' }
  });

  ProtecaModel.HistoEquipement.extend('ProtecaModel.HistoEqSoutirage', {
     'TypeDeversoir': { 'type':'Edm.Int32','nullable':false,'required':true },
     'Autoregule': { 'type':'Edm.Boolean','nullable':false,'required':true },
     'DateControle': { 'type':'Edm.DateTime','nullable':false,'required':true },
     'DateMiseEnServiceRedresseur': { 'type':'Edm.DateTime','nullable':false,'required':true },
     'DatePoseDeversoir': { 'type':'Edm.DateTime' },
     'DateRenouvellementDeversoir': { 'type':'Edm.DateTime' },
     'IntensiteReglage': { 'type':'Edm.Decimal','nullable':false,'required':true },
     'LongueurDeversoir': { 'type':'Edm.Decimal','nullable':false,'required':true },
     'MasseAuMetreLineaire': { 'type':'Edm.Decimal' },
     'PresenceReenclencheur': { 'type':'Edm.Boolean','nullable':false,'required':true },
     'TensionReglage': { 'type':'Edm.Int32','nullable':false,'required':true },
     'CoordDebDeversoirLat': { 'type':'Edm.Decimal' },
     'CoordDebDeversoirLong': { 'type':'Edm.Decimal' },
     'CoordFinDeversoirLat': { 'type':'Edm.Decimal' },
     'CoordFinDeversoirLong': { 'type':'Edm.Decimal' },
     'TypeRedresseur': { 'type':'Edm.String','maxLength':30 },
     'DateMiseEnServiceTelemesure': { 'type':'Edm.DateTime' },
     'PresenceTelemesure': { 'type':'Edm.Boolean','nullable':false,'required':true },
     'RefSousTypeOuvrage': { 'type':'ProtecaModel.RefSousTypeOuvrage','required':true,'inverseProperty':'HistoEqSoutirage' }
  });

  ProtecaModel.HistoEquipement.extend('ProtecaModel.HistoEqFourreauMetallique', {
     'Longueur': { 'type':'Edm.Decimal','nullable':false,'required':true },
     'LibellePp2': { 'type':'Edm.String','maxLength':50 },
     'LibellePortionPp2': { 'type':'Edm.String','maxLength':80 }
  });

  ProtecaModel.HistoEquipement.extend('ProtecaModel.HistoEqPostegaz', {
     'CodePosteGaz': { 'type':'Edm.String','maxLength':30 },
     'TypePoste': { 'type':'Edm.String','maxLength':50 }
  });

  ProtecaModel.HistoEquipement.extend('ProtecaModel.HistoEqTiersCroiseSansLiaison', {
     'NomTiersAssocie': { 'type':'Edm.String','maxLength':30 },
     'PresencePcSurOuvrageTiers': { 'type':'Edm.Boolean','nullable':false,'required':true },
     'TypeFluide': { 'type':'Edm.String','maxLength':30 }
  });

  $data.Entity.extend('ProtecaModel.HistoPp', {
     'CleHistoPp': { 'key':true,'type':'Edm.Int32','nullable':false,'computed':true },
     'CleCommune': { 'type':'Edm.Int32','nullable':false,'required':true },
     'CleLogOuvrage': { 'type':'Edm.Int32','nullable':false,'required':true },
     'CleCategoriePp': { 'type':'Edm.Int32' },
     'CleNiveauSensibilite': { 'type':'Edm.Int32','nullable':false,'required':true },
     'EnumSurfaceTme': { 'type':'Edm.Int32' },
     'EnumSurfaceTms': { 'type':'Edm.Int32' },
     'EnumDureeEnrg': { 'type':'Edm.Int32' },
     'EnumPolarisation': { 'type':'Edm.Int32' },
     'Libelle': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':40 },
     'LibellePortion': { 'type':'Edm.String','maxLength':80 },
     'Pk': { 'type':'Edm.Decimal','nullable':false,'required':true },
     'Commentaire': { 'type':'Edm.String','maxLength':500 },
     'DateMajCommentaire': { 'type':'Edm.DateTime' },
     'PositionnementPostal': { 'type':'Edm.String','maxLength':500 },
     'CommentairePositionnement': { 'type':'Edm.String','maxLength':500 },
     'CourantsVagabonds': { 'type':'Edm.Boolean','nullable':false,'required':true },
     'CourantsAlternatifsInduits': { 'type':'Edm.Boolean','nullable':false,'required':true },
     'ElectrodeEnterreeAmovible': { 'type':'Edm.Boolean','nullable':false,'required':true },
     'TemoinEnterreAmovible': { 'type':'Edm.Boolean','nullable':false,'required':true },
     'TemoinMetalliqueDeSurface': { 'type':'Edm.Boolean','nullable':false,'required':true },
     'PositionGpsLat': { 'type':'Edm.Decimal' },
     'PositionGpsLong': { 'type':'Edm.Decimal' },
     'CoordonneeGpsFiabilisee': { 'type':'Edm.Boolean','nullable':false,'required':true },
     'DateMiseEnService': { 'type':'Edm.DateTime' },
     'PresenceTelemesure': { 'type':'Edm.Boolean','nullable':false,'required':true },
     'DateMiseEnServiceTelemesure': { 'type':'Edm.DateTime' },
     'PpPoste': { 'type':'Edm.Boolean','nullable':false,'required':true },
     'Supprime': { 'type':'Edm.Boolean','nullable':false,'required':true },
     'DateMajPp': { 'type':'Edm.DateTime','nullable':false,'required':true },
     'CategoriePp': { 'type':'ProtecaModel.CategoriePp','inverseProperty':'HistoPp' },
     'RefEnumValeur': { 'type':'ProtecaModel.RefEnumValeur','inverseProperty':'HistoPp' },
     'RefCommune': { 'type':'ProtecaModel.RefCommune','required':true,'inverseProperty':'HistoPp' },
     'RefEnumValeur1': { 'type':'ProtecaModel.RefEnumValeur','inverseProperty':'HistoPp1' },
     'RefNiveauSensibilitePp': { 'type':'ProtecaModel.RefNiveauSensibilitePp','required':true,'inverseProperty':'HistoPp' },
     'LogOuvrage': { 'type':'ProtecaModel.LogOuvrage','required':true,'inverseProperty':'HistoPp' },
     'RefEnumValeur2': { 'type':'ProtecaModel.RefEnumValeur','inverseProperty':'HistoPp2' },
     'RefEnumValeur3': { 'type':'ProtecaModel.RefEnumValeur','inverseProperty':'HistoPp3' },
     'LogOuvrage1': { 'type':'Array','elementType':'ProtecaModel.LogOuvrage','inverseProperty':'HistoPp1' }
  });

  $data.Entity.extend('ProtecaModel.Image', {
     'CleImage': { 'key':true,'type':'Edm.Int32','nullable':false,'computed':true },
     'CleEquipement': { 'type':'Edm.Int32' },
     'ClePp': { 'type':'Edm.Int32' },
     'EnumTypeImage': { 'type':'Edm.Int32','nullable':false,'required':true },
     'Image1': { 'type':'Edm.Binary','nullable':false,'required':true,'maxLength':Number.POSITIVE_INFINITY },
     'EqEquipement': { 'type':'ProtecaModel.EqEquipement','inverseProperty':'Images' },
     'Pp': { 'type':'ProtecaModel.Pp','inverseProperty':'Images' },
     'RefEnumValeur': { 'type':'ProtecaModel.RefEnumValeur','required':true,'inverseProperty':'Images' }
  });

  $data.Entity.extend('ProtecaModel.InsInstrument', {
     'CleInstrument': { 'key':true,'type':'Edm.Int32','nullable':false,'computed':true },
     'CleSecteur': { 'type':'Edm.Int32' },
     'CleAgence': { 'type':'Edm.Int32' },
     'CleRegion': { 'type':'Edm.Int32' },
     'Libelle': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':50 },
     'Supprime': { 'type':'Edm.Boolean','nullable':false,'required':true },
     'GeoAgence': { 'type':'ProtecaModel.GeoAgence','inverseProperty':'InsInstrument' },
     'GeoRegion': { 'type':'ProtecaModel.GeoRegion','inverseProperty':'InsInstrument' },
     'GeoSecteur': { 'type':'ProtecaModel.GeoSecteur','inverseProperty':'InsInstrument' },
     'InstrumentsUtilises': { 'type':'Array','elementType':'ProtecaModel.InstrumentsUtilises','inverseProperty':'InsInstrument' }
  });

  $data.Entity.extend('ProtecaModel.InstrumentsUtilises', {
     'CleInsUtilises': { 'key':true,'type':'Edm.Int32','nullable':false,'computed':true },
     'CleInstrument': { 'type':'Edm.Int32','nullable':false,'required':true },
     'CleVisite': { 'type':'Edm.Int32','nullable':false,'required':true },
     'InsInstrument': { 'type':'ProtecaModel.InsInstrument','required':true,'inverseProperty':'InstrumentsUtilises' },
     'Visite': { 'type':'ProtecaModel.Visite','required':true,'inverseProperty':'InstrumentsUtilises' }
  });

  $data.Entity.extend('ProtecaModel.LogOuvrage', {
     'CleLogOuvrage': { 'key':true,'type':'Edm.Int32','nullable':false,'computed':true },
     'CleEnsElectrique': { 'type':'Edm.Int32' },
     'ClePortion': { 'type':'Edm.Int32' },
     'CleEquipement': { 'type':'Edm.Int32' },
     'ClePp': { 'type':'Edm.Int32' },
     'CleUtilisateur': { 'type':'Edm.Int32','nullable':false,'required':true },
     'CleHistoEquipement': { 'type':'Edm.Int32' },
     'CleHistoPp': { 'type':'Edm.Int32' },
     'EnumTypeModification': { 'type':'Edm.Int32','nullable':false,'required':true },
     'ListeChamps': { 'type':'Edm.String','maxLength':2000 },
     'DateHistorisation': { 'type':'Edm.DateTime','nullable':false,'required':true },
     'EnsembleElectrique': { 'type':'ProtecaModel.EnsembleElectrique','inverseProperty':'LogOuvrage' },
     'EqEquipement': { 'type':'ProtecaModel.EqEquipement','inverseProperty':'LogOuvrage' },
     'HistoEquipement': { 'type':'Array','elementType':'ProtecaModel.HistoEquipement','inverseProperty':'LogOuvrage' },
     'HistoEquipement1': { 'type':'ProtecaModel.HistoEquipement','inverseProperty':'LogOuvrage1' },
     'HistoPp': { 'type':'Array','elementType':'ProtecaModel.HistoPp','inverseProperty':'LogOuvrage' },
     'HistoPp1': { 'type':'ProtecaModel.HistoPp','inverseProperty':'LogOuvrage1' },
     'PortionIntegrite': { 'type':'ProtecaModel.PortionIntegrite','inverseProperty':'LogOuvrage' },
     'Pp': { 'type':'ProtecaModel.Pp','inverseProperty':'LogOuvrage' },
     'RefEnumValeur': { 'type':'ProtecaModel.RefEnumValeur','required':true,'inverseProperty':'LogOuvrage' },
     'UsrUtilisateur': { 'type':'ProtecaModel.UsrUtilisateur','required':true,'inverseProperty':'LogOuvrage' }
  });

  $data.Entity.extend('ProtecaModel.MesClassementMesure', {
     'CleClassementMesure': { 'key':true,'type':'Edm.Int32','nullable':false,'computed':true },
     'CleTypeMesure': { 'type':'Edm.Int32','nullable':false,'required':true },
     'CourantsVagabons': { 'type':'Edm.Boolean','nullable':false,'required':true },
     'CourantsAlternatifsInduits': { 'type':'Edm.Boolean','nullable':false,'required':true },
     'ElectrodeEnterreeAmovible': { 'type':'Edm.Boolean','nullable':false,'required':true },
     'TemoinEnterre': { 'type':'Edm.Boolean','nullable':false,'required':true },
     'TemoinDeSurface': { 'type':'Edm.Boolean','nullable':false,'required':true },
     'Telemesure': { 'type':'Edm.Boolean','nullable':false,'required':true },
     'MesTypeMesure': { 'type':'ProtecaModel.MesTypeMesure','required':true,'inverseProperty':'MesClassementMesure' }
  });

  $data.Entity.extend('ProtecaModel.MesCoutMesure', {
     'CleCoutMesure': { 'key':true,'type':'Edm.Int32','nullable':false,'computed':true },
     'EnumDureeEnregistrement': { 'type':'Edm.Int32' },
     'EnumTempsPolarisation': { 'type':'Edm.Int32' },
     'EnumTypeEval': { 'type':'Edm.Int32','nullable':false,'required':true },
     'CleTypeEq': { 'type':'Edm.Int32','nullable':false,'required':true },
     'Temps': { 'type':'Edm.Decimal' },
     'Cout': { 'type':'Edm.Decimal' },
     'RefEnumValeur': { 'type':'ProtecaModel.RefEnumValeur','required':true,'inverseProperty':'MesCoutMesure' },
     'TypeEquipement': { 'type':'ProtecaModel.TypeEquipement','required':true,'inverseProperty':'MesCoutMesure' },
     'RefEnumValeur1': { 'type':'ProtecaModel.RefEnumValeur','inverseProperty':'MesCoutMesure1' },
     'RefEnumValeur2': { 'type':'ProtecaModel.RefEnumValeur','inverseProperty':'MesCoutMesure2' }
  });

  $data.Entity.extend('ProtecaModel.MesModeleMesure', {
     'CleModeleMesure': { 'key':true,'type':'Edm.Int32','nullable':false,'computed':true },
     'CleUnite': { 'type':'Edm.Int32','nullable':false,'required':true },
     'CleTypeEq': { 'type':'Edm.Int32','nullable':false,'required':true },
     'EnumTypeGraphique': { 'type':'Edm.Int32' },
     'Libelle': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':80 },
     'LibGenerique': { 'type':'Edm.String','maxLength':50 },
     'NumeroOrdre': { 'type':'Edm.Int32','nullable':false,'required':true },
     'MesurePositive': { 'type':'Edm.Boolean','nullable':false,'required':true },
     'MesUnite': { 'type':'ProtecaModel.MesUnite','required':true,'inverseProperty':'MesModeleMesure' },
     'TypeEquipement': { 'type':'ProtecaModel.TypeEquipement','required':true,'inverseProperty':'MesModeleMesure' },
     'RefEnumValeur': { 'type':'ProtecaModel.RefEnumValeur','inverseProperty':'MesModeleMesure' },
     'MesNiveauProtection': { 'type':'Array','elementType':'ProtecaModel.MesNiveauProtection','inverseProperty':'MesModeleMesure' },
     'MesTypeMesure': { 'type':'Array','elementType':'ProtecaModel.MesTypeMesure','inverseProperty':'MesModeleMesure' }
  });

  $data.Entity.extend('ProtecaModel.MesNiveauProtection', {
     'CleNiveauProtection': { 'key':true,'type':'Edm.Int32','nullable':false,'computed':true },
     'CleModeleMesure': { 'type':'Edm.Int32','nullable':false,'required':true },
     'ClePortion': { 'type':'Edm.Int32' },
     'ClePp': { 'type':'Edm.Int32' },
     'CleEquipement': { 'type':'Edm.Int32' },
     'SeuilMini': { 'type':'Edm.Decimal' },
     'SeuilMaxi': { 'type':'Edm.Decimal' },
     'EqEquipement': { 'type':'ProtecaModel.EqEquipement','inverseProperty':'MesNiveauProtection' },
     'MesModeleMesure': { 'type':'ProtecaModel.MesModeleMesure','required':true,'inverseProperty':'MesNiveauProtection' },
     'PortionIntegrite': { 'type':'ProtecaModel.PortionIntegrite','inverseProperty':'MesNiveauProtection' },
     'Pp': { 'type':'ProtecaModel.Pp','inverseProperty':'MesNiveauProtection' }
  });

  $data.Entity.extend('ProtecaModel.MesTypeMesure', {
     'CleTypeMesure': { 'key':true,'type':'Edm.Int32','nullable':false,'computed':true },
     'TypeEvaluation': { 'type':'Edm.Int32','nullable':false,'required':true },
     'NiveauType': { 'type':'Edm.Int32','nullable':false,'required':true },
     'CleModeleMesure': { 'type':'Edm.Int32','nullable':false,'required':true },
     'LibTypeMesure': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':80 },
     'LibNivAutre': { 'type':'Edm.String','maxLength':50 },
     'MesureEnService': { 'type':'Edm.Boolean','nullable':false,'required':true },
     'MesureComplementaire': { 'type':'Edm.Boolean','nullable':false,'required':true },
     'NumeroOrdre': { 'type':'Edm.Int32','nullable':false,'required':true },
     'MesClassementMesure': { 'type':'Array','elementType':'ProtecaModel.MesClassementMesure','inverseProperty':'MesTypeMesure' },
     'MesModeleMesure': { 'type':'ProtecaModel.MesModeleMesure','required':true,'inverseProperty':'MesTypeMesure' },
     'RefEnumValeur': { 'type':'ProtecaModel.RefEnumValeur','required':true,'inverseProperty':'MesTypeMesure' },
     'RefEnumValeur1': { 'type':'ProtecaModel.RefEnumValeur','required':true,'inverseProperty':'MesTypeMesure1' },
     'MesMesure': { 'type':'Array','elementType':'ProtecaModel.MesMesure','inverseProperty':'MesTypeMesure' }
  });

  $data.Entity.extend('ProtecaModel.MesUnite', {
     'CleUnite': { 'key':true,'type':'Edm.Int32','nullable':false,'computed':true },
     'TypeDonnee': { 'type':'Edm.Int32','nullable':false,'required':true },
     'Libelle': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':50 },
     'Symbole': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':5 },
     'NombreDeDecimales': { 'type':'Edm.Int32' },
     'MesModeleMesure': { 'type':'Array','elementType':'ProtecaModel.MesModeleMesure','inverseProperty':'MesUnite' },
     'RefEnumValeur': { 'type':'ProtecaModel.RefEnumValeur','required':true,'inverseProperty':'MesUnite' }
  });

  $data.Entity.extend('ProtecaModel.ParametreAction', {
     'CleParametreAction': { 'key':true,'type':'Edm.Int32','nullable':false,'computed':true },
     'EnumTypeAction': { 'type':'Edm.Int32','nullable':false,'required':true },
     'EnumCategorieAnomalie': { 'type':'Edm.Int32','nullable':false,'required':true },
     'EnumPriorite': { 'type':'Edm.Int32','nullable':false,'required':true },
     'EnumDelaiRealisation': { 'type':'Edm.Int32','nullable':false,'required':true },
     'Temps': { 'type':'Edm.Decimal' },
     'Cout': { 'type':'Edm.Decimal' },
     'Codification': { 'type':'Edm.String','maxLength':30 },
     'RefEnumValeur': { 'type':'ProtecaModel.RefEnumValeur','required':true,'inverseProperty':'ParametreAction' },
     'RefEnumValeur1': { 'type':'ProtecaModel.RefEnumValeur','required':true,'inverseProperty':'ParametreAction1' },
     'RefEnumValeur2': { 'type':'ProtecaModel.RefEnumValeur','required':true,'inverseProperty':'ParametreAction2' },
     'RefEnumValeur3': { 'type':'ProtecaModel.RefEnumValeur','required':true,'inverseProperty':'ParametreAction3' }
  });

  $data.Entity.extend('ProtecaModel.PiSecteurs', {
     'ClePortionSecteurs': { 'key':true,'type':'Edm.Int32','nullable':false,'computed':true },
     'CleSecteur': { 'type':'Edm.Int32','nullable':false,'required':true },
     'ClePortion': { 'type':'Edm.Int32','nullable':false,'required':true },
     'GeoSecteur': { 'type':'ProtecaModel.GeoSecteur','required':true,'inverseProperty':'PiSecteurs' },
     'PortionIntegrite': { 'type':'ProtecaModel.PortionIntegrite','required':true,'inverseProperty':'PiSecteurs' }
  });

  $data.Entity.extend('ProtecaModel.PortionIntegrite', {
     'ClePortion': { 'key':true,'type':'Edm.Int32','nullable':false,'computed':true },
     'CleEnsElectrique': { 'type':'Edm.Int32','nullable':false,'required':true },
     'CleRevetement': { 'type':'Edm.Int32','nullable':false,'required':true },
     'CleDiametre': { 'type':'Edm.Int32','nullable':false,'required':true },
     'CleCommuneDepart': { 'type':'Edm.Int32' },
     'CleCommuneArrivee': { 'type':'Edm.Int32' },
     'Code': { 'type':'Edm.String','maxLength':16 },
     'Libelle': { 'type':'Edm.String','maxLength':80 },
     'CodeGmao': { 'type':'Edm.String','maxLength':16 },
     'DateMiseEnService': { 'type':'Edm.DateTime' },
     'DatePose': { 'type':'Edm.DateTime' },
     'Commentaire': { 'type':'Edm.String','maxLength':500 },
     'DateMajCommentaire': { 'type':'Edm.DateTime' },
     'Longueur': { 'type':'Edm.Decimal' },
     'Idtroncon': { 'type':'Edm.Int32' },
     'Supprime': { 'type':'Edm.Boolean','nullable':false,'required':true },
     'Branchement': { 'type':'Edm.Boolean','nullable':false,'required':true },
     'Compositions': { 'type':'Array','elementType':'ProtecaModel.Composition','inverseProperty':'PortionIntegrite' },
     'EnsembleElectrique': { 'type':'ProtecaModel.EnsembleElectrique','required':true,'inverseProperty':'PortionIntegrite' },
     'LogOuvrage': { 'type':'Array','elementType':'ProtecaModel.LogOuvrage','inverseProperty':'PortionIntegrite' },
     'MesNiveauProtection': { 'type':'Array','elementType':'ProtecaModel.MesNiveauProtection','inverseProperty':'PortionIntegrite' },
     'PiSecteurs': { 'type':'Array','elementType':'ProtecaModel.PiSecteurs','inverseProperty':'PortionIntegrite' },
     'RefCommune': { 'type':'ProtecaModel.RefCommune','inverseProperty':'PortionIntegrite' },
     'RefCommune1': { 'type':'ProtecaModel.RefCommune','inverseProperty':'PortionIntegrite1' },
     'RefDiametre': { 'type':'ProtecaModel.RefDiametre','required':true,'inverseProperty':'PortionIntegrite' },
     'RefRevetement': { 'type':'ProtecaModel.RefRevetement','required':true,'inverseProperty':'PortionIntegrite' },
     'Pps': { 'type':'Array','elementType':'ProtecaModel.Pp','inverseProperty':'PortionIntegrite' },
     'PortionIntegriteAnAction': { 'type':'Array','elementType':'ProtecaModel.PortionIntegriteAnAction','inverseProperty':'PortionIntegrite' }
  });

  $data.Entity.extend('ProtecaModel.Pp', {
     'ClePp': { 'key':true,'type':'Edm.Int32','nullable':false,'computed':true },
     'CleCommune': { 'type':'Edm.Int32','nullable':false,'required':true },
     'CleNiveauSensibilite': { 'type':'Edm.Int32','nullable':false,'required':true },
     'CleCategoriePp': { 'type':'Edm.Int32' },
     'ClePpOrigine': { 'type':'Edm.Int32' },
     'EnumSurfaceTme': { 'type':'Edm.Int32' },
     'CleUtilisateur': { 'type':'Edm.Int32','nullable':false,'required':true },
     'EnumSurfaceTms': { 'type':'Edm.Int32' },
     'EnumDureeEnrg': { 'type':'Edm.Int32' },
     'CleSecteur': { 'type':'Edm.Int32','nullable':false,'required':true },
     'EnumPolarisation': { 'type':'Edm.Int32' },
     'ClePortion': { 'type':'Edm.Int32','nullable':false,'required':true },
     'Libelle': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':40 },
     'Pk': { 'type':'Edm.Decimal','nullable':false,'required':true },
     'Commentaire': { 'type':'Edm.String','maxLength':500 },
     'DateMajCommentaire': { 'type':'Edm.DateTime' },
     'PositionnementPostal': { 'type':'Edm.String','maxLength':500 },
     'CommentairePositionnement': { 'type':'Edm.String','maxLength':500 },
     'CourantsVagabonds': { 'type':'Edm.Boolean','nullable':false,'required':true },
     'CourantsAlternatifsInduits': { 'type':'Edm.Boolean','nullable':false,'required':true },
     'ElectrodeEnterreeAmovible': { 'type':'Edm.Boolean','nullable':false,'required':true },
     'TemoinEnterreAmovible': { 'type':'Edm.Boolean','nullable':false,'required':true },
     'TemoinMetalliqueDeSurface': { 'type':'Edm.Boolean','nullable':false,'required':true },
     'PositionGpsLat': { 'type':'Edm.Decimal' },
     'PositionGpsLong': { 'type':'Edm.Decimal' },
     'CoordonneeGpsFiabilisee': { 'type':'Edm.Boolean','nullable':false,'required':true },
     'DateMiseEnService': { 'type':'Edm.DateTime' },
     'PresenceDUneTelemesure': { 'type':'Edm.Boolean','nullable':false,'required':true },
     'DateMiseEnServiceTelemesure': { 'type':'Edm.DateTime' },
     'PpPoste': { 'type':'Edm.Boolean','nullable':false,'required':true },
     'Supprime': { 'type':'Edm.Boolean','nullable':false,'required':true },
     'DateMajPp': { 'type':'Edm.DateTime','nullable':false,'required':true },
     'CleUtiDdeDeverrouillage': { 'type':'Edm.Int32' },
     'DdeDeverrouillageCoordGps': { 'type':'Edm.Boolean','nullable':false,'required':true },
     'DateDdeDeverrouillageCoordGps': { 'type':'Edm.DateTime' },
     'CategoriePp': { 'type':'ProtecaModel.CategoriePp','inverseProperty':'Pps' },
     'Compositions': { 'type':'Array','elementType':'ProtecaModel.Composition','inverseProperty':'Pp' },
     'EqEquipement': { 'type':'Array','elementType':'ProtecaModel.EqEquipement','inverseProperty':'Pp' },
     'EqEquipementTmp': { 'type':'Array','elementType':'ProtecaModel.EqEquipementTmp','inverseProperty':'Pp2' },
     'EqFourreauMetallique': { 'type':'Array','elementType':'ProtecaModel.EqFourreauMetallique','inverseProperty':'Pp2' },
     'EqLiaisonInterne': { 'type':'Array','elementType':'ProtecaModel.EqLiaisonInterne','inverseProperty':'Pp2' },
     'EqRaccordIsolant': { 'type':'Array','elementType':'ProtecaModel.EqRaccordIsolant','inverseProperty':'Pp2' },
     'GeoSecteur': { 'type':'ProtecaModel.GeoSecteur','required':true,'inverseProperty':'Pps' },
     'Images': { 'type':'Array','elementType':'ProtecaModel.Image','inverseProperty':'Pp' },
     'LogOuvrage': { 'type':'Array','elementType':'ProtecaModel.LogOuvrage','inverseProperty':'Pp' },
     'MesNiveauProtection': { 'type':'Array','elementType':'ProtecaModel.MesNiveauProtection','inverseProperty':'Pp' },
     'PortionIntegrite': { 'type':'ProtecaModel.PortionIntegrite','required':true,'inverseProperty':'Pps' },
     'RefCommune': { 'type':'ProtecaModel.RefCommune','required':true,'inverseProperty':'Pps' },
     'RefEnumValeur': { 'type':'ProtecaModel.RefEnumValeur','inverseProperty':'Pps' },
     'PpJumelee': { 'type':'Array','elementType':'ProtecaModel.PpJumelee','inverseProperty':'Pp' },
     'PpJumelee1': { 'type':'Array','elementType':'ProtecaModel.PpJumelee','inverseProperty':'Pp1' },
     'RefEnumValeur1': { 'type':'ProtecaModel.RefEnumValeur','inverseProperty':'Pps1' },
     'Pp1': { 'type':'Array','elementType':'ProtecaModel.Pp','inverseProperty':'Pp2' },
     'Pp2': { 'type':'ProtecaModel.Pp','inverseProperty':'Pp1' },
     'UsrUtilisateur': { 'type':'ProtecaModel.UsrUtilisateur','required':true,'inverseProperty':'Pps' },
     'RefEnumValeur2': { 'type':'ProtecaModel.RefEnumValeur','inverseProperty':'Pps2' },
     'RefEnumValeur3': { 'type':'ProtecaModel.RefEnumValeur','inverseProperty':'Pps3' },
     'RefNiveauSensibilitePp': { 'type':'ProtecaModel.RefNiveauSensibilitePp','required':true,'inverseProperty':'Pps' },
     'UsrUtilisateur1': { 'type':'ProtecaModel.UsrUtilisateur','inverseProperty':'Pps1' },
     'Visites': { 'type':'Array','elementType':'ProtecaModel.Visite','inverseProperty':'Pp' },
     'PpTmp': { 'type':'Array','elementType':'ProtecaModel.PpTmp','inverseProperty':'Pp' }
  });

  $data.Entity.extend('ProtecaModel.PpJumelee', {
     'ClePpJumelee': { 'key':true,'type':'Edm.Int32','nullable':false,'computed':true },
     'PpClePp': { 'type':'Edm.Int32','nullable':false,'required':true },
     'ClePp': { 'type':'Edm.Int32','nullable':false,'required':true },
     'Pp': { 'type':'ProtecaModel.Pp','required':true,'inverseProperty':'PpJumelee' },
     'Pp1': { 'type':'ProtecaModel.Pp','required':true,'inverseProperty':'PpJumelee1' }
  });

  $data.Entity.extend('ProtecaModel.RefCommune', {
     'CleCommune': { 'key':true,'type':'Edm.Int32','nullable':false,'computed':true },
     'Libelle': { 'type':'Edm.String','maxLength':45 },
     'LibelleMajuscule': { 'type':'Edm.String','maxLength':45 },
     'CodeDepartement': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':3 },
     'CodeCommune': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':3 },
     'Idmicado': { 'type':'Edm.Int32' },
     'CodeInsee': { 'type':'Edm.String','maxLength':5 },
     'HistoPp': { 'type':'Array','elementType':'ProtecaModel.HistoPp','inverseProperty':'RefCommune' },
     'PortionIntegrite': { 'type':'Array','elementType':'ProtecaModel.PortionIntegrite','inverseProperty':'RefCommune' },
     'PortionIntegrite1': { 'type':'Array','elementType':'ProtecaModel.PortionIntegrite','inverseProperty':'RefCommune1' },
     'Pps': { 'type':'Array','elementType':'ProtecaModel.Pp','inverseProperty':'RefCommune' }
  });

  $data.Entity.extend('ProtecaModel.RefDiametre', {
     'CleDiametre': { 'key':true,'type':'Edm.Int32','nullable':false,'computed':true },
     'Libelle': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':80 },
     'Code': { 'type':'Edm.String','maxLength':40 },
     'Idmicado': { 'type':'Edm.Int32' },
     'PortionIntegrite': { 'type':'Array','elementType':'ProtecaModel.PortionIntegrite','inverseProperty':'RefDiametre' }
  });

  $data.Entity.extend('ProtecaModel.RefEnumValeur', {
     'CleEnumValeur': { 'key':true,'type':'Edm.Int32','nullable':false,'computed':true },
     'Libelle': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':100 },
     'LibelleCourt': { 'type':'Edm.String','maxLength':10 },
     'NumeroOrdre': { 'type':'Edm.Int32','nullable':false,'required':true },
     'CodeGroupe': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':30 },
     'Valeur': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':100 },
     'AnAction': { 'type':'Array','elementType':'ProtecaModel.AnAction','inverseProperty':'RefEnumValeur' },
     'AnAnalyse': { 'type':'Array','elementType':'ProtecaModel.AnAnalyse','inverseProperty':'RefEnumValeur' },
     'Compositions': { 'type':'Array','elementType':'ProtecaModel.Composition','inverseProperty':'RefEnumValeur' },
     'EnsembleElectrique': { 'type':'Array','elementType':'ProtecaModel.EnsembleElectrique','inverseProperty':'RefEnumValeur' },
     'EnsembleElectrique1': { 'type':'Array','elementType':'ProtecaModel.EnsembleElectrique','inverseProperty':'RefEnumValeur1' },
     'EqPile': { 'type':'Array','elementType':'ProtecaModel.EqPile','inverseProperty':'RefEnumValeur' },
     'EqRaccordIsolant': { 'type':'Array','elementType':'ProtecaModel.EqRaccordIsolant','inverseProperty':'RefEnumValeur' },
     'EqRaccordIsolant1': { 'type':'Array','elementType':'ProtecaModel.EqRaccordIsolant','inverseProperty':'RefEnumValeur1' },
     'HistoAdmin': { 'type':'Array','elementType':'ProtecaModel.HistoAdmin','inverseProperty':'RefEnumValeur' },
     'HistoEqPile': { 'type':'Array','elementType':'ProtecaModel.HistoEqPile','inverseProperty':'RefEnumValeur' },
     'HistoEqRaccordIsolant': { 'type':'Array','elementType':'ProtecaModel.HistoEqRaccordIsolant','inverseProperty':'RefEnumValeur' },
     'HistoEqRaccordIsolant1': { 'type':'Array','elementType':'ProtecaModel.HistoEqRaccordIsolant','inverseProperty':'RefEnumValeur1' },
     'HistoPp': { 'type':'Array','elementType':'ProtecaModel.HistoPp','inverseProperty':'RefEnumValeur' },
     'HistoPp1': { 'type':'Array','elementType':'ProtecaModel.HistoPp','inverseProperty':'RefEnumValeur1' },
     'HistoPp2': { 'type':'Array','elementType':'ProtecaModel.HistoPp','inverseProperty':'RefEnumValeur2' },
     'HistoPp3': { 'type':'Array','elementType':'ProtecaModel.HistoPp','inverseProperty':'RefEnumValeur3' },
     'Images': { 'type':'Array','elementType':'ProtecaModel.Image','inverseProperty':'RefEnumValeur' },
     'LogOuvrage': { 'type':'Array','elementType':'ProtecaModel.LogOuvrage','inverseProperty':'RefEnumValeur' },
     'MesCoutMesure': { 'type':'Array','elementType':'ProtecaModel.MesCoutMesure','inverseProperty':'RefEnumValeur' },
     'MesCoutMesure1': { 'type':'Array','elementType':'ProtecaModel.MesCoutMesure','inverseProperty':'RefEnumValeur1' },
     'MesCoutMesure2': { 'type':'Array','elementType':'ProtecaModel.MesCoutMesure','inverseProperty':'RefEnumValeur2' },
     'MesModeleMesure': { 'type':'Array','elementType':'ProtecaModel.MesModeleMesure','inverseProperty':'RefEnumValeur' },
     'MesTypeMesure': { 'type':'Array','elementType':'ProtecaModel.MesTypeMesure','inverseProperty':'RefEnumValeur' },
     'MesTypeMesure1': { 'type':'Array','elementType':'ProtecaModel.MesTypeMesure','inverseProperty':'RefEnumValeur1' },
     'MesUnite': { 'type':'Array','elementType':'ProtecaModel.MesUnite','inverseProperty':'RefEnumValeur' },
     'ParametreAction': { 'type':'Array','elementType':'ProtecaModel.ParametreAction','inverseProperty':'RefEnumValeur' },
     'ParametreAction1': { 'type':'Array','elementType':'ProtecaModel.ParametreAction','inverseProperty':'RefEnumValeur1' },
     'ParametreAction2': { 'type':'Array','elementType':'ProtecaModel.ParametreAction','inverseProperty':'RefEnumValeur2' },
     'ParametreAction3': { 'type':'Array','elementType':'ProtecaModel.ParametreAction','inverseProperty':'RefEnumValeur3' },
     'Pps': { 'type':'Array','elementType':'ProtecaModel.Pp','inverseProperty':'RefEnumValeur' },
     'Pps1': { 'type':'Array','elementType':'ProtecaModel.Pp','inverseProperty':'RefEnumValeur1' },
     'Pps2': { 'type':'Array','elementType':'ProtecaModel.Pp','inverseProperty':'RefEnumValeur2' },
     'Pps3': { 'type':'Array','elementType':'ProtecaModel.Pp','inverseProperty':'RefEnumValeur3' },
     'RefNiveauSensibilitePp': { 'type':'Array','elementType':'ProtecaModel.RefNiveauSensibilitePp','inverseProperty':'RefEnumValeur' },
     'LogTournee': { 'type':'Array','elementType':'ProtecaModel.LogTournee','inverseProperty':'RefEnumValeur' },
     'Alertes': { 'type':'Array','elementType':'ProtecaModel.Alerte','inverseProperty':'RefEnumValeur' },
     'Visites': { 'type':'Array','elementType':'ProtecaModel.Visite','inverseProperty':'RefEnumValeur' },
     'PpTmp': { 'type':'Array','elementType':'ProtecaModel.PpTmp','inverseProperty':'RefEnumValeur' },
     'PpTmp1': { 'type':'Array','elementType':'ProtecaModel.PpTmp','inverseProperty':'RefEnumValeur1' },
     'PpTmp2': { 'type':'Array','elementType':'ProtecaModel.PpTmp','inverseProperty':'RefEnumValeur2' },
     'PpTmp3': { 'type':'Array','elementType':'ProtecaModel.PpTmp','inverseProperty':'RefEnumValeur3' },
     'Visites1': { 'type':'Array','elementType':'ProtecaModel.Visite','inverseProperty':'RefEnumValeur1' },
     'AnAction1': { 'type':'Array','elementType':'ProtecaModel.AnAction','inverseProperty':'RefEnumValeur1' },
     'AnAction2': { 'type':'Array','elementType':'ProtecaModel.AnAction','inverseProperty':'RefEnumValeur2' }
  });

  $data.Entity.extend('ProtecaModel.RefNiveauSensibilitePp', {
     'CleNiveauSensibilite': { 'key':true,'type':'Edm.Int32','nullable':false,'computed':true },
     'EnumTypeEval': { 'type':'Edm.Int32' },
     'Libelle': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':20 },
     'TypeSensibilite': { 'type':'Edm.Int32','nullable':false,'required':true },
     'CategoriePp': { 'type':'Array','elementType':'ProtecaModel.CategoriePp','inverseProperty':'RefNiveauSensibilitePp' },
     'HistoPp': { 'type':'Array','elementType':'ProtecaModel.HistoPp','inverseProperty':'RefNiveauSensibilitePp' },
     'Pps': { 'type':'Array','elementType':'ProtecaModel.Pp','inverseProperty':'RefNiveauSensibilitePp' },
     'RefEnumValeur': { 'type':'ProtecaModel.RefEnumValeur','inverseProperty':'RefNiveauSensibilitePp' },
     'PpTmp': { 'type':'Array','elementType':'ProtecaModel.PpTmp','inverseProperty':'RefNiveauSensibilitePp' }
  });

  $data.Entity.extend('ProtecaModel.RefRevetement', {
     'CleRevetement': { 'key':true,'type':'Edm.Int32','nullable':false,'computed':true },
     'Libelle': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':80 },
     'Code': { 'type':'Edm.String','maxLength':40 },
     'Idmicado': { 'type':'Edm.Int32' },
     'PortionIntegrite': { 'type':'Array','elementType':'ProtecaModel.PortionIntegrite','inverseProperty':'RefRevetement' }
  });

  $data.Entity.extend('ProtecaModel.RefSousTypeOuvrage', {
     'CleSousTypeOuvrage': { 'key':true,'type':'Edm.Int32','nullable':false,'computed':true },
     'Libelle': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':30 },
     'NumeroOrdre': { 'type':'Edm.Int32','nullable':false,'required':true },
     'CodeGroupe': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':25 },
     'Valeur': { 'type':'Edm.String','maxLength':100 },
     'EqAnodeGalvanique': { 'type':'Array','elementType':'ProtecaModel.EqAnodeGalvanique','inverseProperty':'RefSousTypeOuvrage' },
     'EqDispoEcoulementCourantsAlternatifs': { 'type':'Array','elementType':'ProtecaModel.EqDispoEcoulementCourantsAlternatifs','inverseProperty':'RefSousTypeOuvrage' },
     'EqDrainage': { 'type':'Array','elementType':'ProtecaModel.EqDrainage','inverseProperty':'RefSousTypeOuvrage' },
     'EqLiaisonExterne': { 'type':'Array','elementType':'ProtecaModel.EqLiaisonExterne','inverseProperty':'RefSousTypeOuvrage' },
     'EqLiaisonExterne1': { 'type':'Array','elementType':'ProtecaModel.EqLiaisonExterne','inverseProperty':'RefSousTypeOuvrage1' },
     'EqLiaisonInterne': { 'type':'Array','elementType':'ProtecaModel.EqLiaisonInterne','inverseProperty':'RefSousTypeOuvrage' },
     'EqPile': { 'type':'Array','elementType':'ProtecaModel.EqPile','inverseProperty':'RefSousTypeOuvrage' },
     'EqRaccordIsolant': { 'type':'Array','elementType':'ProtecaModel.EqRaccordIsolant','inverseProperty':'RefSousTypeOuvrage' },
     'EqRaccordIsolant1': { 'type':'Array','elementType':'ProtecaModel.EqRaccordIsolant','inverseProperty':'RefSousTypeOuvrage1' },
     'EqSoutirage': { 'type':'Array','elementType':'ProtecaModel.EqSoutirage','inverseProperty':'RefSousTypeOuvrage' },
     'EqSoutirage1': { 'type':'Array','elementType':'ProtecaModel.EqSoutirage','inverseProperty':'RefSousTypeOuvrage1' },
     'HistoEqAnodeGalvanique': { 'type':'Array','elementType':'ProtecaModel.HistoEqAnodeGalvanique','inverseProperty':'RefSousTypeOuvrage' },
     'HistoEqDispoEcoulementCourantsAlternatifs': { 'type':'Array','elementType':'ProtecaModel.HistoEqDispoEcoulementCourantsAlternatifs','inverseProperty':'RefSousTypeOuvrage' },
     'HistoEqDrainage': { 'type':'Array','elementType':'ProtecaModel.HistoEqDrainage','inverseProperty':'RefSousTypeOuvrage' },
     'HistoEqLiaisonExterne': { 'type':'Array','elementType':'ProtecaModel.HistoEqLiaisonExterne','inverseProperty':'RefSousTypeOuvrage' },
     'HistoEqLiaisonInterne': { 'type':'Array','elementType':'ProtecaModel.HistoEqLiaisonInterne','inverseProperty':'RefSousTypeOuvrage' },
     'HistoEqPile': { 'type':'Array','elementType':'ProtecaModel.HistoEqPile','inverseProperty':'RefSousTypeOuvrage' },
     'HistoEqRaccordIsolant': { 'type':'Array','elementType':'ProtecaModel.HistoEqRaccordIsolant','inverseProperty':'RefSousTypeOuvrage' },
     'HistoEqRaccordIsolant1': { 'type':'Array','elementType':'ProtecaModel.HistoEqRaccordIsolant','inverseProperty':'RefSousTypeOuvrage1' },
     'HistoEqSoutirage': { 'type':'Array','elementType':'ProtecaModel.HistoEqSoutirage','inverseProperty':'RefSousTypeOuvrage' }
  });

  $data.Entity.extend('ProtecaModel.RefUsrAutorisation', {
     'CleAutorisation': { 'key':true,'type':'Edm.Int32','nullable':false,'computed':true },
     'CleGroupe': { 'type':'Edm.Int32' },
     'LibelleAutorisation': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':100 },
     'CodeAutorisation': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':20 },
     'TypePortee': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':6 },
     'RefUsrGroupe': { 'type':'ProtecaModel.RefUsrGroupe','inverseProperty':'RefUsrAutorisation' },
     'UsrRole': { 'type':'Array','elementType':'ProtecaModel.UsrRole','inverseProperty':'RefUsrAutorisation' }
  });

  $data.Entity.extend('ProtecaModel.RefUsrGroupe', {
     'CleGroupe': { 'key':true,'type':'Edm.Int32','nullable':false,'computed':true },
     'LibelleGroupe': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':30 },
     'RefUsrAutorisation': { 'type':'Array','elementType':'ProtecaModel.RefUsrAutorisation','inverseProperty':'RefUsrGroupe' }
  });

  $data.Entity.extend('ProtecaModel.RefUsrPortee', {
     'ClePortee': { 'key':true,'type':'Edm.Int32','nullable':false,'computed':true },
     'CodePortee': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':3 },
     'LibellePortee': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':10 },
     'TypePortee': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':6 },
     'UsrProfil': { 'type':'Array','elementType':'ProtecaModel.UsrProfil','inverseProperty':'RefUsrPortee' },
     'UsrRole': { 'type':'Array','elementType':'ProtecaModel.UsrRole','inverseProperty':'RefUsrPortee' },
     'UsrUtilisateur': { 'type':'Array','elementType':'ProtecaModel.UsrUtilisateur','inverseProperty':'RefUsrPortee' }
  });

  $data.Entity.extend('ProtecaModel.Tournee', {
     'CleTournee': { 'key':true,'type':'Edm.Int32','nullable':false,'computed':true },
     'CleUtilisateur': { 'type':'Edm.Int32' },
     'Libelle': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':50 },
     'CodeTournee': { 'type':'Edm.String','maxLength':10 },
     'Commentaire': { 'type':'Edm.String','maxLength':100 },
     'DateCreation': { 'type':'Edm.DateTime' },
     'Numero': { 'type':'Edm.Int32' },
     'Supprime': { 'type':'Edm.Boolean','nullable':false,'required':true },
     'Verrouille': { 'type':'Edm.Boolean','nullable':false,'required':true },
     'Compositions': { 'type':'Array','elementType':'ProtecaModel.Composition','inverseProperty':'Tournee' },
     'UsrUtilisateur': { 'type':'ProtecaModel.UsrUtilisateur','inverseProperty':'Tournees' },
     'LogTournee': { 'type':'Array','elementType':'ProtecaModel.LogTournee','inverseProperty':'Tournee' }
  });

  $data.Entity.extend('ProtecaModel.TypeEquipement', {
     'CleTypeEq': { 'key':true,'type':'Edm.Int32','nullable':false,'computed':true },
     'Libelle': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':40 },
     'CodeEquipement': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':2 },
     'NumeroOrdre': { 'type':'Edm.Int32','nullable':false,'required':true },
     'CategoriePp': { 'type':'Array','elementType':'ProtecaModel.CategoriePp','inverseProperty':'TypeEquipement' },
     'EqEquipement': { 'type':'Array','elementType':'ProtecaModel.EqEquipement','inverseProperty':'TypeEquipement' },
     'EqEquipementTmp': { 'type':'Array','elementType':'ProtecaModel.EqEquipementTmp','inverseProperty':'TypeEquipement' },
     'HistoEquipement': { 'type':'Array','elementType':'ProtecaModel.HistoEquipement','inverseProperty':'TypeEquipement' },
     'MesCoutMesure': { 'type':'Array','elementType':'ProtecaModel.MesCoutMesure','inverseProperty':'TypeEquipement' },
     'MesModeleMesure': { 'type':'Array','elementType':'ProtecaModel.MesModeleMesure','inverseProperty':'TypeEquipement' }
  });

  $data.Entity.extend('ProtecaModel.UsrProfil', {
     'CleProfil': { 'key':true,'type':'Edm.Int32','nullable':false,'computed':true },
     'ClePortee': { 'type':'Edm.Int32','nullable':false,'required':true },
     'LibelleProfil': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':30 },
     'Editable': { 'type':'Edm.Boolean','nullable':false,'required':true },
     'ProfilAdmin': { 'type':'Edm.Boolean','nullable':false,'required':true },
     'RefUsrPortee': { 'type':'ProtecaModel.RefUsrPortee','required':true,'inverseProperty':'UsrProfil' },
     'UsrRole': { 'type':'Array','elementType':'ProtecaModel.UsrRole','inverseProperty':'UsrProfil' },
     'UsrUtilisateur': { 'type':'Array','elementType':'ProtecaModel.UsrUtilisateur','inverseProperty':'UsrProfil' }
  });

  $data.Entity.extend('ProtecaModel.UsrRole', {
     'CleRole': { 'key':true,'type':'Edm.Int32','nullable':false,'computed':true },
     'CleAutorisation': { 'type':'Edm.Int32','nullable':false,'required':true },
     'CleProfil': { 'type':'Edm.Int32','nullable':false,'required':true },
     'ClePortee': { 'type':'Edm.Int32','nullable':false,'required':true },
     'RefUsrAutorisation': { 'type':'ProtecaModel.RefUsrAutorisation','required':true,'inverseProperty':'UsrRole' },
     'RefUsrPortee': { 'type':'ProtecaModel.RefUsrPortee','required':true,'inverseProperty':'UsrRole' },
     'UsrProfil': { 'type':'ProtecaModel.UsrProfil','required':true,'inverseProperty':'UsrRole' }
  });

  $data.Entity.extend('ProtecaModel.UsrUtilisateur', {
     'CleUtilisateur': { 'key':true,'type':'Edm.Int32','nullable':false,'computed':true },
     'CleSecteur': { 'type':'Edm.Int32' },
     'GestionDesComptes': { 'type':'Edm.Int32','nullable':false,'required':true },
     'CleAgence': { 'type':'Edm.Int32' },
     'CleProfil': { 'type':'Edm.Int32' },
     'Nom': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':20 },
     'Prenom': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':15 },
     'Identifiant': { 'type':'Edm.String','maxLength':10 },
     'Mail': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':70 },
     'Societe': { 'type':'Edm.String','maxLength':30 },
     'Supprime': { 'type':'Edm.Boolean','nullable':false,'required':true },
     'Externe': { 'type':'Edm.Boolean','nullable':false,'required':true },
     'EstPresta': { 'type':'Edm.Boolean','nullable':false,'required':true },
     'AnAction': { 'type':'Array','elementType':'ProtecaModel.AnAction','inverseProperty':'UsrUtilisateur' },
     'AnAction1': { 'type':'Array','elementType':'ProtecaModel.AnAction','inverseProperty':'UsrUtilisateur1' },
     'AnAnalyse': { 'type':'Array','elementType':'ProtecaModel.AnAnalyse','inverseProperty':'UsrUtilisateur' },
     'EqEquipement': { 'type':'Array','elementType':'ProtecaModel.EqEquipement','inverseProperty':'UsrUtilisateur' },
     'GeoAgence': { 'type':'ProtecaModel.GeoAgence','inverseProperty':'UsrUtilisateur' },
     'GeoSecteur': { 'type':'ProtecaModel.GeoSecteur','inverseProperty':'UsrUtilisateur' },
     'LogOuvrage': { 'type':'Array','elementType':'ProtecaModel.LogOuvrage','inverseProperty':'UsrUtilisateur' },
     'Pps': { 'type':'Array','elementType':'ProtecaModel.Pp','inverseProperty':'UsrUtilisateur' },
     'RefUsrPortee': { 'type':'ProtecaModel.RefUsrPortee','required':true,'inverseProperty':'UsrUtilisateur' },
     'Tournees': { 'type':'Array','elementType':'ProtecaModel.Tournee','inverseProperty':'UsrUtilisateur' },
     'UsrProfil': { 'type':'ProtecaModel.UsrProfil','inverseProperty':'UsrUtilisateur' },
     'LogTournee': { 'type':'Array','elementType':'ProtecaModel.LogTournee','inverseProperty':'UsrUtilisateur' },
     'Pps1': { 'type':'Array','elementType':'ProtecaModel.Pp','inverseProperty':'UsrUtilisateur1' },
     'Visites': { 'type':'Array','elementType':'ProtecaModel.Visite','inverseProperty':'UsrUtilisateur' },
     'Visites1': { 'type':'Array','elementType':'ProtecaModel.Visite','inverseProperty':'UsrUtilisateur1' },
     'Visites2': { 'type':'Array','elementType':'ProtecaModel.Visite','inverseProperty':'UsrUtilisateur2' },
     'Visites3': { 'type':'Array','elementType':'ProtecaModel.Visite','inverseProperty':'UsrUtilisateur3' },
     'PpTmp': { 'type':'Array','elementType':'ProtecaModel.PpTmp','inverseProperty':'UsrUtilisateur' }
  });

  $data.Entity.extend('ProtecaModel.LogTournee', {
     'CleLogTournee': { 'key':true,'type':'Edm.Int32','nullable':false,'computed':true },
     'CleTournee': { 'type':'Edm.Int32','nullable':false,'required':true },
     'CleUtilisateur': { 'type':'Edm.Int32','nullable':false,'required':true },
     'EnumTypeModification': { 'type':'Edm.Int32','nullable':false,'required':true },
     'ListeChamps': { 'type':'Edm.String','maxLength':2000 },
     'DateHistorisation': { 'type':'Edm.DateTime','nullable':false,'required':true },
     'Tournee': { 'type':'ProtecaModel.Tournee','required':true,'inverseProperty':'LogTournee' },
     'RefEnumValeur': { 'type':'ProtecaModel.RefEnumValeur','required':true,'inverseProperty':'LogTournee' },
     'UsrUtilisateur': { 'type':'ProtecaModel.UsrUtilisateur','required':true,'inverseProperty':'LogTournee' }
  });

  $data.Entity.extend('ProtecaModel.Alerte', {
     'CleAlerte': { 'key':true,'type':'Edm.Int32','nullable':false,'computed':true },
     'CleVisite': { 'type':'Edm.Int32' },
     'CleMesure': { 'type':'Edm.Int32' },
     'EnumTypeAlerte': { 'type':'Edm.Int32','nullable':false,'required':true },
     'CleAnalyse': { 'type':'Edm.Int32' },
     'Date': { 'type':'Edm.DateTime','nullable':false,'required':true },
     'Supprime': { 'type':'Edm.Boolean','nullable':false,'required':true },
     'AnAnalyseSerieMesure': { 'type':'ProtecaModel.AnAnalyseSerieMesure','inverseProperty':'Alertes' },
     'MesMesure': { 'type':'ProtecaModel.MesMesure','inverseProperty':'Alertes' },
     'Visite': { 'type':'ProtecaModel.Visite','inverseProperty':'Alertes' },
     'RefEnumValeur': { 'type':'ProtecaModel.RefEnumValeur','required':true,'inverseProperty':'Alertes' }
  });

  $data.Entity.extend('ProtecaModel.MesMesure', {
     'CleMesure': { 'key':true,'type':'Edm.Int32','nullable':false,'computed':true },
     'CleTypeMesure': { 'type':'Edm.Int32','nullable':false,'required':true },
     'CleVisite': { 'type':'Edm.Int32','nullable':false,'required':true },
     'Valeur': { 'type':'Edm.Decimal' },
     'Alertes': { 'type':'Array','elementType':'ProtecaModel.Alerte','inverseProperty':'MesMesure' },
     'MesTypeMesure': { 'type':'ProtecaModel.MesTypeMesure','required':true,'inverseProperty':'MesMesure' },
     'Visite': { 'type':'ProtecaModel.Visite','required':true,'inverseProperty':'MesMesure' }
  });

  $data.Entity.extend('ProtecaModel.Visite', {
     'CleVisite': { 'key':true,'type':'Edm.Int32','nullable':false,'computed':true },
     'CleUtilisateurCreation': { 'type':'Edm.Int32' },
     'CleUtilisateurImport': { 'type':'Edm.Int32' },
     'CleUtilisateurMesure': { 'type':'Edm.Int32' },
     'CleEqTmp': { 'type':'Edm.Int32' },
     'CleUtilisateurValidation': { 'type':'Edm.Int32' },
     'EnumTypeEval': { 'type':'Edm.Int32','nullable':false,'required':true },
     'ClePp': { 'type':'Edm.Int32' },
     'CleEquipement': { 'type':'Edm.Int32' },
     'DateVisite': { 'type':'Edm.DateTime' },
     'DateSaisie': { 'type':'Edm.DateTime' },
     'DateImport': { 'type':'Edm.DateTime' },
     'DateValidation': { 'type':'Edm.DateTime' },
     'EstValidee': { 'type':'Edm.Boolean','nullable':false,'required':true },
     'Commentaire': { 'type':'Edm.String','maxLength':500 },
     'RelevePartiel': { 'type':'Edm.Boolean','nullable':false,'required':true },
     'Telemesure': { 'type':'Edm.Boolean','nullable':false,'required':true },
     'ClePpTmp': { 'type':'Edm.Int32' },
     'EnumTypeEvalComposition': { 'type':'Edm.Int32','nullable':false,'required':true },
     'EnumConformiteTournee': { 'type':'Edm.Int32' },
     'Alertes': { 'type':'Array','elementType':'ProtecaModel.Alerte','inverseProperty':'Visite' },
     'AnAnalyseSerieMesure': { 'type':'Array','elementType':'ProtecaModel.AnAnalyseSerieMesure','inverseProperty':'Visite' },
     'EqEquipement': { 'type':'ProtecaModel.EqEquipement','inverseProperty':'Visites' },
     'EqEquipementTmp': { 'type':'ProtecaModel.EqEquipementTmp','inverseProperty':'Visites' },
     'InstrumentsUtilises': { 'type':'Array','elementType':'ProtecaModel.InstrumentsUtilises','inverseProperty':'Visite' },
     'MesMesure': { 'type':'Array','elementType':'ProtecaModel.MesMesure','inverseProperty':'Visite' },
     'Pp': { 'type':'ProtecaModel.Pp','inverseProperty':'Visites' },
     'RefEnumValeur': { 'type':'ProtecaModel.RefEnumValeur','required':true,'inverseProperty':'Visites' },
     'UsrUtilisateur': { 'type':'ProtecaModel.UsrUtilisateur','inverseProperty':'Visites' },
     'UsrUtilisateur1': { 'type':'ProtecaModel.UsrUtilisateur','inverseProperty':'Visites1' },
     'UsrUtilisateur2': { 'type':'ProtecaModel.UsrUtilisateur','inverseProperty':'Visites2' },
     'UsrUtilisateur3': { 'type':'ProtecaModel.UsrUtilisateur','inverseProperty':'Visites3' },
     'AnAnalyseEeVisite': { 'type':'Array','elementType':'ProtecaModel.AnAnalyseEeVisite','inverseProperty':'Visite' },
     'PpTmp': { 'type':'ProtecaModel.PpTmp','inverseProperty':'Visites' },
     'RefEnumValeur1': { 'type':'ProtecaModel.RefEnumValeur','required':true,'inverseProperty':'Visites1' }
  });

  $data.Entity.extend('ProtecaModel.AnAnalyseEeVisite', {
     'CleAnalyseEeVisite': { 'key':true,'type':'Edm.Int32','nullable':false,'computed':true },
     'CleAnalyse': { 'type':'Edm.Int32','nullable':false,'required':true },
     'CleVisite': { 'type':'Edm.Int32','nullable':false,'required':true },
     'AnAnalyseEe': { 'type':'ProtecaModel.AnAnalyseEe','required':true,'inverseProperty':'AnAnalyseEeVisite' },
     'Visite': { 'type':'ProtecaModel.Visite','required':true,'inverseProperty':'AnAnalyseEeVisite' }
  });

  $data.Entity.extend('ProtecaModel.PpTmp', {
     'CourantsVagabonds': { 'type':'Edm.Boolean','nullable':false,'required':true },
     'CourantsAlternatifsInduits': { 'type':'Edm.Boolean','nullable':false,'required':true },
     'ElectrodeEnterreeAmovible': { 'type':'Edm.Boolean','nullable':false,'required':true },
     'TemoinEnterreAmovible': { 'type':'Edm.Boolean','nullable':false,'required':true },
     'TemoinMetalliqueDeSurface': { 'type':'Edm.Boolean','nullable':false,'required':true },
     'PositionGpsLat': { 'type':'Edm.Decimal' },
     'PositionGpsLong': { 'type':'Edm.Decimal' },
     'CoordonneeGpsFiabilisee': { 'type':'Edm.Boolean','nullable':false,'required':true },
     'DdeDeverrouillageCoordGps': { 'type':'Edm.Boolean','nullable':false,'required':true },
     'DateDdeDeverrouillageCoordGps': { 'type':'Edm.DateTime' },
     'PresenceDUneTelemesure': { 'type':'Edm.Boolean','nullable':false,'required':true },
     'ClePpTmp': { 'key':true,'type':'Edm.Int32','nullable':false,'computed':true },
     'CleCategoriePp': { 'type':'Edm.Int32' },
     'ClePp': { 'type':'Edm.Int32','nullable':false,'required':true },
     'EnumPolarisation': { 'type':'Edm.Int32' },
     'CleUtiDdeDeverrouillage': { 'type':'Edm.Int32' },
     'EnumSurfaceTme': { 'type':'Edm.Int32' },
     'EnumDureeEnrg': { 'type':'Edm.Int32' },
     'CleNiveauSensibilite': { 'type':'Edm.Int32','nullable':false,'required':true },
     'EnumSurfaceTms': { 'type':'Edm.Int32' },
     'DateMajPp': { 'type':'Edm.DateTime','nullable':false,'required':true },
     'CategoriePp': { 'type':'ProtecaModel.CategoriePp','inverseProperty':'PpTmp' },
     'Pp': { 'type':'ProtecaModel.Pp','required':true,'inverseProperty':'PpTmp' },
     'RefEnumValeur': { 'type':'ProtecaModel.RefEnumValeur','inverseProperty':'PpTmp' },
     'RefEnumValeur1': { 'type':'ProtecaModel.RefEnumValeur','inverseProperty':'PpTmp1' },
     'RefEnumValeur2': { 'type':'ProtecaModel.RefEnumValeur','inverseProperty':'PpTmp2' },
     'RefEnumValeur3': { 'type':'ProtecaModel.RefEnumValeur','inverseProperty':'PpTmp3' },
     'RefNiveauSensibilitePp': { 'type':'ProtecaModel.RefNiveauSensibilitePp','required':true,'inverseProperty':'PpTmp' },
     'UsrUtilisateur': { 'type':'ProtecaModel.UsrUtilisateur','inverseProperty':'PpTmp' },
     'Visites': { 'type':'Array','elementType':'ProtecaModel.Visite','inverseProperty':'PpTmp' }
  });

  $data.Entity.extend('ProtecaModel.PortionIntegriteAnAction', {
     'Id': { 'key':true,'type':'Edm.Int32','nullable':false,'computed':true },
     'CleAction': { 'type':'Edm.Int32','nullable':false,'required':true },
     'ClePortion': { 'type':'Edm.Int32','nullable':false,'required':true },
     'AnAction': { 'type':'ProtecaModel.AnAction','required':true,'inverseProperty':'PortionIntegriteAnAction' },
     'PortionIntegrite': { 'type':'ProtecaModel.PortionIntegrite','required':true,'inverseProperty':'PortionIntegriteAnAction' }
  });

  $data.EntityContext.extend('Proteca.Web.Models.ProtecaEntities', {
     'RefParametre': { type: $data.EntitySet, elementType: ProtecaModel.RefParametre},
     'GeoEnsembleElectrique': { type: $data.EntitySet, elementType: ProtecaModel.GeoEnsembleElectrique},
     'PortionDates': { type: $data.EntitySet, elementType: ProtecaModel.PortionDates},
     'PpEquipement': { type: $data.EntitySet, elementType: ProtecaModel.PpEquipement},
     'TourneePpEq': { type: $data.EntitySet, elementType: ProtecaModel.TourneePpEq},
     'AlerteDetail': { type: $data.EntitySet, elementType: ProtecaModel.AlerteDetail},
     'GeoEnsElecPortion': { type: $data.EntitySet, elementType: ProtecaModel.GeoEnsElecPortion},
     'GeoEnsElecPortionEqPp': { type: $data.EntitySet, elementType: ProtecaModel.GeoEnsElecPortionEqPp},
     'AnAction': { type: $data.EntitySet, elementType: ProtecaModel.AnAction},
     'AnAnalyse': { type: $data.EntitySet, elementType: ProtecaModel.AnAnalyse},
     'CategoriePp': { type: $data.EntitySet, elementType: ProtecaModel.CategoriePp},
     'Compositions': { type: $data.EntitySet, elementType: ProtecaModel.Composition},
     'EnsembleElectrique': { type: $data.EntitySet, elementType: ProtecaModel.EnsembleElectrique},
     'EqDrainageLiaisonsext': { type: $data.EntitySet, elementType: ProtecaModel.EqDrainageLiaisonsext},
     'EqEquipement': { type: $data.EntitySet, elementType: ProtecaModel.EqEquipement},
     'EqEquipementTmp': { type: $data.EntitySet, elementType: ProtecaModel.EqEquipementTmp},
     'EqSoutirageLiaisonsext': { type: $data.EntitySet, elementType: ProtecaModel.EqSoutirageLiaisonsext},
     'GeoAgence': { type: $data.EntitySet, elementType: ProtecaModel.GeoAgence},
     'GeoRegion': { type: $data.EntitySet, elementType: ProtecaModel.GeoRegion},
     'GeoSecteur': { type: $data.EntitySet, elementType: ProtecaModel.GeoSecteur},
     'HistoAdmin': { type: $data.EntitySet, elementType: ProtecaModel.HistoAdmin},
     'HistoEquipement': { type: $data.EntitySet, elementType: ProtecaModel.HistoEquipement},
     'HistoPp': { type: $data.EntitySet, elementType: ProtecaModel.HistoPp},
     'Images': { type: $data.EntitySet, elementType: ProtecaModel.Image},
     'InsInstrument': { type: $data.EntitySet, elementType: ProtecaModel.InsInstrument},
     'InstrumentsUtilises': { type: $data.EntitySet, elementType: ProtecaModel.InstrumentsUtilises},
     'LogOuvrage': { type: $data.EntitySet, elementType: ProtecaModel.LogOuvrage},
     'MesClassementMesure': { type: $data.EntitySet, elementType: ProtecaModel.MesClassementMesure},
     'MesCoutMesure': { type: $data.EntitySet, elementType: ProtecaModel.MesCoutMesure},
     'MesModeleMesure': { type: $data.EntitySet, elementType: ProtecaModel.MesModeleMesure},
     'MesNiveauProtection': { type: $data.EntitySet, elementType: ProtecaModel.MesNiveauProtection},
     'MesTypeMesure': { type: $data.EntitySet, elementType: ProtecaModel.MesTypeMesure},
     'MesUnite': { type: $data.EntitySet, elementType: ProtecaModel.MesUnite},
     'ParametreAction': { type: $data.EntitySet, elementType: ProtecaModel.ParametreAction},
     'PiSecteurs': { type: $data.EntitySet, elementType: ProtecaModel.PiSecteurs},
     'PortionIntegrite': { type: $data.EntitySet, elementType: ProtecaModel.PortionIntegrite},
     'Pps': { type: $data.EntitySet, elementType: ProtecaModel.Pp},
     'PpJumelee': { type: $data.EntitySet, elementType: ProtecaModel.PpJumelee},
     'RefCommune': { type: $data.EntitySet, elementType: ProtecaModel.RefCommune},
     'RefDiametre': { type: $data.EntitySet, elementType: ProtecaModel.RefDiametre},
     'RefEnumValeur': { type: $data.EntitySet, elementType: ProtecaModel.RefEnumValeur},
     'RefNiveauSensibilitePp': { type: $data.EntitySet, elementType: ProtecaModel.RefNiveauSensibilitePp},
     'RefRevetement': { type: $data.EntitySet, elementType: ProtecaModel.RefRevetement},
     'RefSousTypeOuvrage': { type: $data.EntitySet, elementType: ProtecaModel.RefSousTypeOuvrage},
     'RefUsrAutorisation': { type: $data.EntitySet, elementType: ProtecaModel.RefUsrAutorisation},
     'RefUsrGroupe': { type: $data.EntitySet, elementType: ProtecaModel.RefUsrGroupe},
     'RefUsrPortee': { type: $data.EntitySet, elementType: ProtecaModel.RefUsrPortee},
     'Tournees': { type: $data.EntitySet, elementType: ProtecaModel.Tournee},
     'TypeEquipement': { type: $data.EntitySet, elementType: ProtecaModel.TypeEquipement},
     'UsrProfil': { type: $data.EntitySet, elementType: ProtecaModel.UsrProfil},
     'UsrRole': { type: $data.EntitySet, elementType: ProtecaModel.UsrRole},
     'UsrUtilisateur': { type: $data.EntitySet, elementType: ProtecaModel.UsrUtilisateur},
     'LogTournee': { type: $data.EntitySet, elementType: ProtecaModel.LogTournee},
     'Alertes': { type: $data.EntitySet, elementType: ProtecaModel.Alerte},
     'MesMesure': { type: $data.EntitySet, elementType: ProtecaModel.MesMesure},
     'Visites': { type: $data.EntitySet, elementType: ProtecaModel.Visite},
     'AnAnalyseEeVisite': { type: $data.EntitySet, elementType: ProtecaModel.AnAnalyseEeVisite},
     'PpTmp': { type: $data.EntitySet, elementType: ProtecaModel.PpTmp},
     'PortionIntegriteAnAction': { type: $data.EntitySet, elementType: ProtecaModel.PortionIntegriteAnAction}
  });

  $data.generatedContexts = $data.generatedContexts || [];
  $data.generatedContexts.push(Proteca.Web.Models.ProtecaEntities);
  
      
})(window, $data);
      
    