

/*//////////////////////////////////////////////////////////////////////////////////////
////// Autogenerated by JaySvcUtil.exe http://JayData.org for more info        /////////
//////                             oData  V2                                     /////////
//////////////////////////////////////////////////////////////////////////////////////*/
(function(global, $data, undefined) {

    
  $data.Entity.extend('ProtecaModel.UsrUtilisateur', {
     'CleUtilisateur': { 'key':true,'type':'Edm.Int32','nullable':false,'computed':true },
     'CleSecteur': { 'type':'Edm.Int32' },
     'GestionDesComptes': { 'type':'Edm.Int32','nullable':false,'required':true },
     'CleAgence': { 'type':'Edm.Int32' },
     'CleProfil': { 'type':'Edm.Int32' },
     'Nom': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':20 },
     'Prenom': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':15 },
     'Identifiant': { 'type':'Edm.String','maxLength':10 },
     'Mail': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':70 },
     'Societe': { 'type':'Edm.String','maxLength':30 },
     'Supprime': { 'type':'Edm.Boolean','nullable':false,'required':true },
     'Externe': { 'type':'Edm.Boolean','nullable':false,'required':true },
     'EstPresta': { 'type':'Edm.Boolean','nullable':false,'required':true }
  });

  $data.EntityContext.extend('Proteca.Web.Models.ProtecaEntities', {
     'UsrUtilisateur': { type: $data.EntitySet, elementType: ProtecaModel.UsrUtilisateur}
  });

  $data.generatedContexts = $data.generatedContexts || [];
  $data.generatedContexts.push(Proteca.Web.Models.ProtecaEntities);
  
      
})(window, $data);
      
    