//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proteca.Silverlight.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Rapports {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Rapports() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Proteca.Silverlight.Resources.Rapports", typeof(Rapports).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à /_layouts/ReportServer/RSViewerPage.aspx?rv:RelativeReportUrl=/ProtecaV4/.
        /// </summary>
        public static string printDocumentUrl {
            get {
                return ResourceManager.GetString("printDocumentUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Proteca_Fiches_Equipements_{0}.rdl&amp;rv:HeaderArea=None&amp;rv:ParamMode=Hidden&amp;rs:Command=Render&amp;rp:Cle_EQ={1}.
        /// </summary>
        public static string printFicheEquipementFileName {
            get {
                return ResourceManager.GetString("printFicheEquipementFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Proteca_RANA[DETAIL]_Rapport_Analyse_Annexe_5_TAB8.rdl&amp;rv:HeaderArea=None&amp;rv:ParamMode=Hidden&amp;rs:Command=Render&amp;rp:Cle_Analyse_EE={0}.
        /// </summary>
        public static string RANA_Rapport_Analyse_Annexe5_ECD_FileName {
            get {
                return ResourceManager.GetString("RANA_Rapport_Analyse_Annexe5_ECD_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tableaux de mesure ECD.
        /// </summary>
        public static string RANA_Rapport_Analyse_Annexe5_ECD_Lbl {
            get {
                return ResourceManager.GetString("RANA_Rapport_Analyse_Annexe5_ECD_Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Proteca_RANA[DETAIL]_Rapport_Analyse_Annexe_6.rdl&amp;rv:HeaderArea=None&amp;rv:ParamMode=Hidden&amp;rs:Command=Render&amp;rp:EE={0}.
        /// </summary>
        public static string RANA_Rapport_Analyse_Annexe6_FileName {
            get {
                return ResourceManager.GetString("RANA_Rapport_Analyse_Annexe6_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Classification des PP....
        /// </summary>
        public static string RANA_Rapport_Analyse_Annexe6_Lbl {
            get {
                return ResourceManager.GetString("RANA_Rapport_Analyse_Annexe6_Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Proteca_RANA_Rapport_Analyse.rdl&amp;rp:Cle_Analyse_EE={0}&amp;rp:Annexe1={1}&amp;rp:Annexe2={2}&amp;rp:Annexe3={3}&amp;rp:Annexe4={4}&amp;rp:Annexe5={5}&amp;rp:Annexe6={6}&amp;rp:Id_Auteur={7}.
        /// </summary>
        public static string RANA_Rapport_Analyse_FileName {
            get {
                return ResourceManager.GetString("RANA_Rapport_Analyse_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Générer un rapport.
        /// </summary>
        public static string RANA_Rapport_Analyse_Lbl {
            get {
                return ResourceManager.GetString("RANA_Rapport_Analyse_Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Proteca_RBAG_Bilan_Agent.rdl&amp;rp:Region={0}&amp;rp:Agence={1}&amp;rp:Secteur={2}.
        /// </summary>
        public static string RBAG_Bilan_Agent_FileName {
            get {
                return ResourceManager.GetString("RBAG_Bilan_Agent_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bilan par Agent.
        /// </summary>
        public static string RBAG_Bilan_Agent_Lbl {
            get {
                return ResourceManager.GetString("RBAG_Bilan_Agent_Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Proteca_RBGEO_Bilan_Geographique.rdl&amp;rp:Region={0}&amp;rp:Agence={1}&amp;rp:Secteur={2}.
        /// </summary>
        public static string RBGEO_Bilan_Geo_FileName {
            get {
                return ResourceManager.GetString("RBGEO_Bilan_Geo_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bilan Géographique.
        /// </summary>
        public static string RBGEO_Bilan_Geo_Lbl {
            get {
                return ResourceManager.GetString("RBGEO_Bilan_Geo_Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Proteca_RFAC_Fiche_Action.rdl&amp;rp:CleAction={0}.
        /// </summary>
        public static string RFAC_Fiche_Action_FileName {
            get {
                return ResourceManager.GetString("RFAC_Fiche_Action_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fiche Action.
        /// </summary>
        public static string RFAC_Fiche_Action_Lbl {
            get {
                return ResourceManager.GetString("RFAC_Fiche_Action_Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Proteca_RFTO_Tournee_Composition.rdl&amp;rv:HeaderArea=None&amp;rp:Region={0}&amp;rp:Agence={1}&amp;rp:Secteur={2}.
        /// </summary>
        public static string RFTO_Composition_FileName {
            get {
                return ResourceManager.GetString("RFTO_Composition_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Proteca_RFTO_Tournee_Composition.rdl&amp;rv:HeaderArea=None&amp;rv:ParamMode=Hidden&amp;rs:Command=Render&amp;rp:Region={0}&amp;rp:Agence={1}&amp;rp:Secteur={2}&amp;rp:EE={3}&amp;rp:Portion={4}&amp;rp:TO_sup={5}&amp;rp:Tournee={6}.
        /// </summary>
        public static string RFTO_Composition_FileName_Extended {
            get {
                return ResourceManager.GetString("RFTO_Composition_FileName_Extended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tournées et Compositions.
        /// </summary>
        public static string RFTO_Composition_Lbl {
            get {
                return ResourceManager.GetString("RFTO_Composition_Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Proteca_RFVI_Fiche_Visite_Tournee.rdl.
        /// </summary>
        public static string RFVI_Visite_Tournee_FileName {
            get {
                return ResourceManager.GetString("RFVI_Visite_Tournee_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Proteca_RFVI_Fiche_Visite_Tournee.rdl&amp;rv:HeaderArea=None&amp;rv:ParamMode=Hidden&amp;rs:Command=Render&amp;rp:Region={0}&amp;rp:Agence={1}&amp;rp:Secteur={2}&amp;rp:EE={3}&amp;rp:Portion={4}&amp;rp:MesureBase={5}&amp;rp:Tournée={6}.
        /// </summary>
        public static string RFVI_Visite_Tournee_FileName_Extended {
            get {
                return ResourceManager.GetString("RFVI_Visite_Tournee_FileName_Extended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fiche de la tournée.
        /// </summary>
        public static string RFVI_Visite_Tournee_Lbl {
            get {
                return ResourceManager.GetString("RFVI_Visite_Tournee_Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Proteca_RGRAPH_Distance.rdl&amp;rp:Region={0}&amp;rp:Agence={1}&amp;rp:Secteur={2}.
        /// </summary>
        public static string RGRAPH_Distance_FileName {
            get {
                return ResourceManager.GetString("RGRAPH_Distance_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Graphes sur la distance.
        /// </summary>
        public static string RGRAPH_Distance_Lbl {
            get {
                return ResourceManager.GetString("RGRAPH_Distance_Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Proteca_RGRAPH_Histo_DR.rdl&amp;rp:Region={0}&amp;rp:Agence={1}&amp;rp:Secteur={2}.
        /// </summary>
        public static string RGRAPH_Histo_DR_FileName {
            get {
                return ResourceManager.GetString("RGRAPH_Histo_DR_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Historique drainage.
        /// </summary>
        public static string RGRAPH_Histo_DR_Lbl {
            get {
                return ResourceManager.GetString("RGRAPH_Histo_DR_Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Proteca_RGRAPH_Histo_PP.rdl&amp;rp:Region={0}&amp;rp:Agence={1}&amp;rp:Secteur={2}.
        /// </summary>
        public static string RGRAPH_Histo_PP_FileName {
            get {
                return ResourceManager.GetString("RGRAPH_Histo_PP_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Historique PP.
        /// </summary>
        public static string RGRAPH_Histo_PP_Lbl {
            get {
                return ResourceManager.GetString("RGRAPH_Histo_PP_Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Proteca_RGRAPH_Histo_SO.rdl&amp;rp:Region={0}&amp;rp:Agence={1}&amp;rp:Secteur={2}.
        /// </summary>
        public static string RGRAPH_Histo_SO_FileName {
            get {
                return ResourceManager.GetString("RGRAPH_Histo_SO_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Historique soutirage.
        /// </summary>
        public static string RGRAPH_Histo_SO_Lbl {
            get {
                return ResourceManager.GetString("RGRAPH_Histo_SO_Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Proteca_RGRAPH_Potentiel_Cana.rdl&amp;rp:Region={0}&amp;rp:Agence={1}&amp;rp:Secteur={2}.
        /// </summary>
        public static string RGRAPH_Potentiel_Cana_FileName {
            get {
                return ResourceManager.GetString("RGRAPH_Potentiel_Cana_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Historique Potentiel Cana.
        /// </summary>
        public static string RGRAPH_Potentiel_Cana_Lbl {
            get {
                return ResourceManager.GetString("RGRAPH_Potentiel_Cana_Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Proteca_RLAC_Tableau_Suivi_Fiches_Action.rdl&amp;rv:HeaderArea=None&amp;rp:Region={0}&amp;rp:Agence={1}&amp;rp:Secteur={2}.
        /// </summary>
        public static string RLAC_Liste_Action_FileName {
            get {
                return ResourceManager.GetString("RLAC_Liste_Action_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liste des Fiches Action.
        /// </summary>
        public static string RLAC_Liste_Action_Lbl {
            get {
                return ResourceManager.GetString("RLAC_Liste_Action_Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Proteca_RLAN_Liste_Analyse.rdl&amp;rp:Region={0}&amp;rp:Agence={1}&amp;rp:Secteur={2}.
        /// </summary>
        public static string RLAN_Liste_Analyse_FileName {
            get {
                return ResourceManager.GetString("RLAN_Liste_Analyse_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Analyses par région.
        /// </summary>
        public static string RLAN_Liste_Analyse_Lbl {
            get {
                return ResourceManager.GetString("RLAN_Liste_Analyse_Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Proteca_RLCEQ_Liste_Complete_Equipements.rdl&amp;rv:HeaderArea=None&amp;rp:Region={0}&amp;rp:Agence={1}&amp;rp:Secteur={2}.
        /// </summary>
        public static string RLCEQ_Liste_EQ_ALL_FileName {
            get {
                return ResourceManager.GetString("RLCEQ_Liste_EQ_ALL_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liste Complète des Equipements.
        /// </summary>
        public static string RLCEQ_Liste_EQ_ALL_Lbl {
            get {
                return ResourceManager.GetString("RLCEQ_Liste_EQ_ALL_Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Proteca_RLEE_Liste_Ens_Electrique.rdl&amp;rv:HeaderArea=None&amp;rp:Region={0}&amp;rp:Agence={1}&amp;rp:Secteur={2}.
        /// </summary>
        public static string RLEE_Liste_EE_FileName {
            get {
                return ResourceManager.GetString("RLEE_Liste_EE_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liste des Ensembles Electriques.
        /// </summary>
        public static string RLEE_Liste_EE_Lbl {
            get {
                return ResourceManager.GetString("RLEE_Liste_EE_Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Proteca_RLEM_Liste_Equipements_Mesures.rdl&amp;rv:HeaderArea=None&amp;rp:Region={0}&amp;rp:Agence={1}&amp;rp:Secteur={2}.
        /// </summary>
        public static string RLEM_Liste_EQ_Mesures_FileName {
            get {
                return ResourceManager.GetString("RLEM_Liste_EQ_Mesures_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liste des Equipements Mesurés.
        /// </summary>
        public static string RLEM_Liste_EQ_Mesures_Lbl {
            get {
                return ResourceManager.GetString("RLEM_Liste_EQ_Mesures_Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Proteca_RLEQ_Liste_Equipements.rdl&amp;rv:HeaderArea=None&amp;rp:Region={0}&amp;rp:Agence={1}&amp;rp:Secteur={2}.
        /// </summary>
        public static string RLEQ_Liste_EQ_FileName {
            get {
                return ResourceManager.GetString("RLEQ_Liste_EQ_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liste des Equipements.
        /// </summary>
        public static string RLEQ_Liste_EQ_Lbl {
            get {
                return ResourceManager.GetString("RLEQ_Liste_EQ_Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Proteca_RLGRDF_Liaison_GRDF.rdl&amp;rv:HeaderArea=None&amp;rp:Region={0}&amp;rp:Agence={1}&amp;rp:Secteur={2}.
        /// </summary>
        public static string RLGRDF_Liaison_GRDF_FileName {
            get {
                return ResourceManager.GetString("RLGRDF_Liaison_GRDF_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tableau Liaison GrDF.
        /// </summary>
        public static string RLGRDF_Liaison_GRDF_Lbl {
            get {
                return ResourceManager.GetString("RLGRDF_Liaison_GRDF_Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Proteca_RLMES_Liste_Mesures.rdl&amp;rv:HeaderArea=None&amp;rp:Region={0}&amp;rp:Agence={1}&amp;rp:Secteur={2}.
        /// </summary>
        public static string RLMES_Liste_Mesures_FileName {
            get {
                return ResourceManager.GetString("RLMES_Liste_Mesures_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liste des Mesures.
        /// </summary>
        public static string RLMES_Liste_Mesures_Lbl {
            get {
                return ResourceManager.GetString("RLMES_Liste_Mesures_Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Proteca_RLP_Liste_Portions.rdl&amp;rv:HeaderArea=None&amp;rp:Region={0}&amp;rp:Agence={1}&amp;rp:Secteur={2}.
        /// </summary>
        public static string RLP_Liste_Portion_FileName {
            get {
                return ResourceManager.GetString("RLP_Liste_Portion_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liste des Portions.
        /// </summary>
        public static string RLP_Liste_Portion_Lbl {
            get {
                return ResourceManager.GetString("RLP_Liste_Portion_Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Proteca_RLRI_Liste_RI.rdl&amp;rv:HeaderArea=None&amp;rp:Region={0}&amp;rp:Agence={1}&amp;rp:Secteur={2}.
        /// </summary>
        public static string RLRI_Liste_RI_FileName {
            get {
                return ResourceManager.GetString("RLRI_Liste_RI_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liste des Raccords Isolants.
        /// </summary>
        public static string RLRI_Liste_RI_Lbl {
            get {
                return ResourceManager.GetString("RLRI_Liste_RI_Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Proteca_RMEICA_Bilan_PC.rdl&amp;rp:Region={0}&amp;rp:Agence={1}&amp;rp:Secteur={2}.
        /// </summary>
        public static string RMEICA_Bilan_PC_FileName {
            get {
                return ResourceManager.GetString("RMEICA_Bilan_PC_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bilan PC : MEICA.
        /// </summary>
        public static string RMEICA_Bilan_PC_Lbl {
            get {
                return ResourceManager.GetString("RMEICA_Bilan_PC_Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Proteca_RMES_Liste_Modeles_Mesures.rdl&amp;rv:HeaderArea=None.
        /// </summary>
        public static string RMES_Liste_Modeles_Mesures_FileName {
            get {
                return ResourceManager.GetString("RMES_Liste_Modeles_Mesures_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liste des Modèles de Mesure.
        /// </summary>
        public static string RMES_Liste_Modeles_Mesures_Lbl {
            get {
                return ResourceManager.GetString("RMES_Liste_Modeles_Mesures_Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Proteca_RPRO_Liste_Profils.rdl&amp;rv:HeaderArea=None.
        /// </summary>
        public static string RPRO_Liste_Profils_FileName {
            get {
                return ResourceManager.GetString("RPRO_Liste_Profils_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liste des Profils.
        /// </summary>
        public static string RPRO_Liste_Profils_Lbl {
            get {
                return ResourceManager.GetString("RPRO_Liste_Profils_Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Proteca_RSUIVI_Suivi_EG_ECD.rdl&amp;rp:Region={0}.
        /// </summary>
        public static string RSUIVI_Suivi_EG_ECD_FileName {
            get {
                return ResourceManager.GetString("RSUIVI_Suivi_EG_ECD_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suivi des EG, ECD.
        /// </summary>
        public static string RSUIVI_Suivi_EG_ECD_Lbl {
            get {
                return ResourceManager.GetString("RSUIVI_Suivi_EG_ECD_Lbl", resourceCulture);
            }
        }
    }
}
